import { describe, it, expect } from 'vitest';
import {
  autoresponseSuppressionReason,
  outboundMessageIdPattern,
  ownOutboundReason,
  ticketCreationLoopReason,
} from './loopPrevention';
import type { NormalizedInboundEmail } from './types';

function email(over: Partial<NormalizedInboundEmail>): NormalizedInboundEmail {
  return {
    provider: 'mailgun', providerMessageId: 'm', to: 'acme@tickets.example.com',
    from: 'jane@customer.com', subject: 's', text: 't', attachments: [], raw: {},
    ...over,
  };
}

describe('autoresponseSuppressionReason', () => {
  it('allows a normal human sender (returns null)', () => {
    expect(autoresponseSuppressionReason(email({}), 'tickets.example.com')).toBeNull();
  });

  it('suppresses when Auto-Submitted is present and not "no"', () => {
    expect(autoresponseSuppressionReason(email({ autoSubmitted: 'auto-replied' }), 'tickets.example.com')).toBe('auto-submitted');
    expect(autoresponseSuppressionReason(email({ autoSubmitted: 'no' }), 'tickets.example.com')).toBeNull();
  });

  it('reads the Auto-Submitted keyword CFWS-aware, so "no" with a comment still allows the ack (review F1)', () => {
    // The keyword is `no` regardless of RFC-5322 comments/whitespace around it, so
    // these must NOT suppress the acknowledgement.
    expect(autoresponseSuppressionReason(email({ autoSubmitted: 'no (generated by gateway)' }), 'tickets.example.com')).toBeNull();
    expect(autoresponseSuppressionReason(email({ autoSubmitted: '(gateway) no' }), 'tickets.example.com')).toBeNull();
    expect(autoresponseSuppressionReason(email({ autoSubmitted: '  no  ' }), 'tickets.example.com')).toBeNull();
    // A real auto keyword (even with a comment or params) still suppresses the ack.
    expect(autoresponseSuppressionReason(email({ autoSubmitted: '(vacation) auto-replied' }), 'tickets.example.com')).toBe('auto-submitted');
    expect(autoresponseSuppressionReason(email({ autoSubmitted: 'auto-generated; x=y' }), 'tickets.example.com')).toBe('auto-submitted');
    // Absent/blank ⇒ no suppression.
    expect(autoresponseSuppressionReason(email({ autoSubmitted: '' }), 'tickets.example.com')).toBeNull();
    expect(autoresponseSuppressionReason(email({}), 'tickets.example.com')).toBeNull();
  });

  it('suppresses on Precedence bulk/list/junk', () => {
    for (const p of ['bulk', 'list', 'junk', 'Bulk']) {
      expect(autoresponseSuppressionReason(email({ precedence: p }), 'tickets.example.com')).toBe('precedence');
    }
  });

  it('suppresses no-reply / mailer-daemon / postmaster local-parts', () => {
    expect(autoresponseSuppressionReason(email({ from: 'no-reply@x.com' }), 'tickets.example.com')).toBe('system-sender');
    expect(autoresponseSuppressionReason(email({ from: 'noreply@x.com' }), 'tickets.example.com')).toBe('system-sender');
    expect(autoresponseSuppressionReason(email({ from: 'MAILER-DAEMON@x.com' }), 'tickets.example.com')).toBe('system-sender');
    expect(autoresponseSuppressionReason(email({ from: 'postmaster@x.com' }), 'tickets.example.com')).toBe('system-sender');
  });

  it('suppresses self-loop (sender on our own inbound domain)', () => {
    expect(autoresponseSuppressionReason(email({ from: 'acme@tickets.example.com' }), 'tickets.example.com')).toBe('self-domain');
  });

  it('suppresses the auto-reply on X-Loop presence (but still lets the ticket be created)', () => {
    // X-Loop = the sender runs its own loop-guard; we must not auto-reply, but the
    // mail still becomes a ticket (review #5, finding 3 — moved out of ticket suppression).
    expect(autoresponseSuppressionReason(email({ xLoop: 'help@partner.example.com' }), 'tickets.example.com')).toBe('x-loop');
    expect(autoresponseSuppressionReason(email({ xLoop: '   ' }), 'tickets.example.com')).toBeNull();
    expect(autoresponseSuppressionReason(email({ xLoop: undefined }), 'tickets.example.com')).toBeNull();
  });

  it('does not suppress when inbound domain is unconfigured', () => {
    expect(autoresponseSuppressionReason(email({ from: 'acme@tickets.example.com' }), undefined)).toBeNull();
  });
});

const INBOUND_DOMAIN = 'tickets.example.com';

describe('outboundMessageIdPattern (derived from outboundThreading.ts)', () => {
  // The generator emits exactly two shapes (services/inboundEmail/outboundThreading.ts):
  //   ticketThreadAnchor:  `<ticket-${ticketId}@${d}>`
  //   commentMessageId:    `<ticket-${ticketId}-${commentId}@${d}>`
  // so the pattern is `<ticket-` + anything that is not @ / < / > / space,
  // then the inbound domain.
  const pattern = outboundMessageIdPattern(INBOUND_DOMAIN);

  it('matches both generator shapes', () => {
    expect(pattern.test('<ticket-11111111-1111-4111-8111-111111111111@tickets.example.com>')).toBe(true);
    expect(pattern.test('<ticket-11111111-1111-4111-8111-111111111111-c0ffee00-0000-4000-8000-000000000001@tickets.example.com>')).toBe(true);
  });

  it('is case-insensitive on the domain, as Message-IDs are in practice', () => {
    expect(pattern.test('<TICKET-abc@TICKETS.EXAMPLE.COM>')).toBe(true);
  });

  it('does not match another domain, another prefix, or a lookalike suffix', () => {
    expect(pattern.test('<ticket-abc@tickets.evil.example>')).toBe(false);
    expect(pattern.test('<quote-abc@tickets.example.com>')).toBe(false);
    expect(pattern.test('<ticket-abc@x.tickets.example.com>')).toBe(false);
    expect(pattern.test('<abc@tickets.example.com>')).toBe(false);
  });

  it('escapes the dots in the domain so they are not wildcards', () => {
    expect(outboundMessageIdPattern('tickets.example.com').test('<ticket-a@ticketsXexampleXcom>')).toBe(false);
  });
});

describe('ownOutboundReason (spec §8.5)', () => {
  it('recognises the outbound marker', () => {
    expect(ownOutboundReason(email({ outboundMarker: '1' }), INBOUND_DOMAIN)).toBe('outbound-marker');
    // Any non-empty value counts: forging it only gets the forger's own mail
    // ignored, so there is nothing to gain by being strict about the value.
    expect(ownOutboundReason(email({ outboundMarker: 'yes' }), INBOUND_DOMAIN)).toBe('outbound-marker');
    expect(ownOutboundReason(email({ outboundMarker: '  ' }), INBOUND_DOMAIN)).toBeNull();
  });

  it('recognises our own Message-ID', () => {
    expect(ownOutboundReason(
      email({ messageId: '<ticket-t1-c1@tickets.example.com>' }), INBOUND_DOMAIN,
    )).toBe('own-message-id');
  });

  it('leaves a customer reply alone — its In-Reply-To is ours, its Message-ID is not', () => {
    expect(ownOutboundReason(email({
      messageId: '<CAF=abc@mail.example.com>',
      inReplyTo: '<ticket-t1@tickets.example.com>',
      references: ['<ticket-t1@tickets.example.com>'],
    }), INBOUND_DOMAIN)).toBeNull();
  });

  // Spec §8.5, explicitly: inbound mail is NOT suppressed by sending domain or
  // identity address. With a root sending domain every technician's address is
  // on it, and a technician may legitimately write from the shared mailbox.
  it('processes a technician writing FROM the partner identity address', () => {
    expect(ownOutboundReason(
      email({ from: 'support@mail.acme.test', messageId: '<abc@mail.acme.test>' }), INBOUND_DOMAIN,
    )).toBeNull();
  });

  it('is inert when no inbound domain is configured, except for the marker', () => {
    expect(ownOutboundReason(email({ messageId: '<ticket-t1@tickets.example.com>' }), null)).toBeNull();
    expect(ownOutboundReason(email({ outboundMarker: '1' }), null)).toBe('outbound-marker');
  });

  it('returns null for ordinary inbound mail', () => {
    expect(ownOutboundReason(email({}), INBOUND_DOMAIN)).toBeNull();
  });
});

describe('ticketCreationLoopReason', () => {
  it('lets a normal human message through (null)', () => {
    expect(ticketCreationLoopReason(email({}))).toBeNull();
  });

  it('suppresses Auto-Submitted: auto-replied (a loop reply), incl. RFC-3834 parameters', () => {
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied' }))).toBe('auto-replied');
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'Auto-Replied' }))).toBe('auto-replied');
    // Parameterized header must still match the keyword (finding 8)...
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied; x-foo=bar' }))).toBe('auto-replied');
    // ...a trailing RFC 5322 comment...
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied (vacation)' }))).toBe('auto-replied');
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied (out of office); x=y' }))).toBe('auto-replied');
    // ...and a LEADING comment / CFWS (finding 8), incl. DEEP nesting and escaped
    // parens (RFC 5322 §3.2.2), which need a real scanner not a regex (review #4).
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(vacation) auto-replied' }))).toBe('auto-replied');
    expect(ticketCreationLoopReason(email({ autoSubmitted: '  (a (nested)) auto-replied; foo=bar' }))).toBe('auto-replied');
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(a (b (c))) auto-replied' }))).toBe('auto-replied');
    // Backslash-escaped parens inside the leading comment (literal `\(` / `\)`).
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(vacation \\(away) auto-replied' }))).toBe('auto-replied');
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(vacation \\) away) auto-replied' }))).toBe('auto-replied');
  });

  it('does NOT match auto-replied when it sits INSIDE a comment, not as the keyword (review #4)', () => {
    // The whole comment is CFWS and is skipped; the real keyword follows it.
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(x \\) auto-replied (y)) no' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ autoSubmitted: '(x \\) auto-replied (y)) auto-generated' }))).toBeNull();
  });

  it('does NOT treat a different token as auto-replied (exact keyword only)', () => {
    // Guards the bounded-token match: these are distinct tokens, not the keyword.
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied2' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-replied.foo' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'auto-generated' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ autoSubmitted: 'no' }))).toBeNull();
  });

  it('does NOT suppress Auto-Submitted: auto-generated (device/copier notifications are real tickets)', () => {
    // The load-bearing case: a copier/monitoring/backup email that MSPs want as a ticket,
    // even when it also carries X-Auto-Response-Suppress: All (a "do not auto-reply" hint,
    // not a loop). It must still create a ticket.
    expect(ticketCreationLoopReason(email({
      autoSubmitted: 'auto-generated',
      from: 'no-reply@copier.example.com',
    }))).toBeNull();
  });

  it('suppresses ONLY an explicit null Return-Path (<>), not empty/ordinary paths', () => {
    expect(ticketCreationLoopReason(email({ returnPath: '<>' }))).toBe('null-return-path');
    expect(ticketCreationLoopReason(email({ returnPath: '  <>  ' }))).toBe('null-return-path');
    // CFWS around/inside the angle-addr (RFC 5322) is still the null path.
    expect(ticketCreationLoopReason(email({ returnPath: '< >' }))).toBe('null-return-path');
    expect(ticketCreationLoopReason(email({ returnPath: '<> (auto-generated)' }))).toBe('null-return-path');
    expect(ticketCreationLoopReason(email({ returnPath: '(bounce) <>' }))).toBe('null-return-path');
    expect(ticketCreationLoopReason(email({ returnPath: '(a \\(nested) <>' }))).toBe('null-return-path');
    // Empty string is NOT treated as a bounce (avoids false positives on a stripped header).
    expect(ticketCreationLoopReason(email({ returnPath: '' }))).toBeNull();
    // A comment-only header strips to '' and must NOT be read as a bounce.
    expect(ticketCreationLoopReason(email({ returnPath: '(bounce)' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ returnPath: '<bob@customer.com>' }))).toBeNull();
    // A real address decorated with CFWS must NOT match the null path.
    expect(ticketCreationLoopReason(email({ returnPath: '<bob@customer.com> (sales)' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ returnPath: undefined }))).toBeNull();
    expect(ticketCreationLoopReason(email({ returnPath: null }))).toBeNull();
  });

  it('does NOT suppress ticket creation on X-Loop (we never set it outbound, so it is not a Breeze loop)', () => {
    // X-Loop moved to autoresponse suppression (review #5, finding 3): dropping the
    // ticket on any inbound X-Loop would discard legitimate forwarded/gatewayed
    // support mail. It gates only the auto-REPLY now (see autoresponseSuppressionReason).
    expect(ticketCreationLoopReason(email({ xLoop: 'help@partner.example.com' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ xLoop: '' }))).toBeNull();
  });

  it('does NOT suppress on Precedence: bulk or system local-parts (those only gate the auto-reply)', () => {
    expect(ticketCreationLoopReason(email({ precedence: 'bulk' }))).toBeNull();
    expect(ticketCreationLoopReason(email({ from: 'no-reply@x.com' }))).toBeNull();
  });
});
