/**
 * Route-module MCP coverage (#6141, A-W06).
 * Tools indicate an existing surface, not parity for every endpoint in a module.
 * Gaps are frozen in __tests__/mcp-coverage.test.ts and may only shrink.
 * Keep entries explicit: new route files must make a deliberate coverage choice.
 */
export type McpCoverageEntry =
  | { tools: readonly string[] }
  | { exempt: McpExemptReason; note?: string }
  | { gap: string };

export type McpExemptReason =
  | 'agent_transport'
  | 'identity'
  | 'platform_admin'
  | 'inbound_integration'
  | 'portal'
  | 'addin_surface'
  | 'device_helper'
  | 'mcp_transport'
  | 'internal_plumbing'
  /**
   * A one-time, irreversible-by-default migration an operator runs by hand.
   * Deliberately NOT agent-reachable: the spec gives conversion no AI tool
   * (docs/superpowers/specs/monitoring/2026-09-19-alerting-consolidation-design.md
   * §AI / MCP tools lists no conversion row), the routes are MFA- and
   * governance-gated, and a preview must be read by a human before the
   * matching convert call is made.
   */
  | 'human_only_migration'
  /**
   * Partner-level administration of an EXTERNAL VENDOR CONSOLE connection and
   * the tenant bookkeeping it requires: storing/rotating the vendor login,
   * mapping a discovered vendor customer onto a Breeze organization, and
   * linking a vendor device row to a Breeze device. Deliberately not
   * agent-reachable — these writes decide which tenant a third party's data
   * lands under, and the credential routes are MFA- plus
   * partner-wide-manage-gated. The agent-facing READ surface for backup health
   * is `GET /backup/health` (#6008 W03), which carries its own tools.
   */
  | 'vendor_console_admin'
  /**
   * Caller verification (#6354) — the anti-vishing control itself. Starting,
   * attesting, cancelling or overriding a verification, binding a canonical
   * identity to a contact, and editing the policy floors are all decisions
   * about WHETHER A CALLER IS WHO THEY CLAIM TO BE. An agent-reachable tool
   * here would be the vishing vector the feature exists to close: a
   * prompt-injected or socially-engineered agent could attest a caller's
   * identity, bind an attacker's phone number as canonical, or lower the
   * policy floor, and every downstream control would then read as satisfied.
   * Every write on this router is `organizations:write` + `requireMfa()`
   * precisely so a HUMAN with a second factor is the only actor that can
   * decide one. The read side is deliberately excluded too: the verification
   * record carries challenge and destination provenance material that is
   * classified `excludedSensitive` in the tenant export policy.
   */
  | 'human_only_verification'
  /**
   * Evidence of a customer's agreement attached to an MSP-recorded ("accept on
   * behalf") quote acceptance (#6633) — a signed PDF, PO scan, or email export
   * a dispute reviewer relies on. Accepting on behalf is itself human-only (the
   * spec gives it no AI tool: it commits the customer to an invoice and
   * contracts), and an agent that could attach or replace the supporting file
   * could fabricate the proof behind a money-committing record. Download is
   * excluded with it: the file is internal, never shown to the customer, and
   * is read by a human reviewer from the quote page.
   */
  | 'human_only_legal_evidence';

export const MCP_COVERAGE: Readonly<Record<string, McpCoverageEntry>> = {
  'accessReviews.ts': { gap: '#6141' },
  'accounting/index.ts': { gap: '#6141' },
  'actionIntents.ts': { gap: '#6141' },
  'admin/abuse.ts': { exempt: 'platform_admin' },
  'admin/aiKillState.ts': { exempt: 'platform_admin' },
  'admin/aiToolUsage.ts': { exempt: 'platform_admin' },
  'admin/desktopFinalization.ts': { exempt: 'platform_admin' },
  'admin/exchangeRates.ts': { exempt: 'platform_admin' },
  'admin/llmProviderCatalog.ts': { exempt: 'platform_admin' },
  'admin/sendingDomains.ts': { exempt: 'platform_admin' },
  'admin/tenantErasure.ts': { exempt: 'platform_admin' },
  'admin/tenantExport.ts': { exempt: 'platform_admin' },
  'admin/trust.ts': { exempt: 'platform_admin' },
  'admin/trustAct.ts': { exempt: 'platform_admin' },
  'agentRollback.ts': { gap: '#6141' },
  'agentVersions.ts': { tools: ['query_agent_versions', 'trigger_agent_upgrade'] },
  'agentWs.ts': { exempt: 'agent_transport', note: 'Agent WebSocket command and telemetry transport.' },
  'agents/bootPerformance.ts': { exempt: 'agent_transport' },
  'agents/changes.ts': { exempt: 'agent_transport' },
  'agents/commands.ts': { exempt: 'agent_transport' },
  'agents/connections.ts': { exempt: 'agent_transport' },
  'agents/download.ts': { exempt: 'agent_transport' },
  'agents/elevationRequests.ts': { exempt: 'agent_transport' },
  'agents/enrollment.ts': { exempt: 'agent_transport' },
  'agents/eventlogs.ts': { exempt: 'agent_transport' },
  'agents/heartbeat.ts': { exempt: 'agent_transport' },
  'agents/inventory.ts': { exempt: 'agent_transport' },
  'agents/logs.ts': { exempt: 'agent_transport' },
  'agents/mtls.ts': { exempt: 'agent_transport' },
  'agents/pamObservations.ts': { exempt: 'agent_transport' },
  'agents/pamReconciliation.ts': { exempt: 'agent_transport' },
  'agents/patches.ts': { exempt: 'agent_transport' },
  'agents/peripherals.ts': { exempt: 'agent_transport' },
  'agents/processSample.ts': { exempt: 'agent_transport' },
  'agents/recoveryKeys.ts': { exempt: 'agent_transport' },
  'agents/reliability.ts': { exempt: 'agent_transport' },
  'agents/security.ts': { exempt: 'agent_transport' },
  'agents/sessions.ts': { exempt: 'agent_transport' },
  'agents/state.ts': { exempt: 'agent_transport' },
  'agents/token.ts': { exempt: 'agent_transport' },
  'agents/unifiTelemetry.ts': { exempt: 'agent_transport' },
  'agents/uninstallIntent.ts': { exempt: 'agent_transport' },
  'agents/wingetBootstrap.ts': { exempt: 'agent_transport' },
  'ai.ts': { gap: '#6141' },
  'ai/scriptPolicy.ts': { gap: '#6141' },
  'ai/scriptProposals.ts': { tools: ['propose_script', 'get_script_proposal'] },
  'aiAgentSchedules.ts': { gap: '#6141' },
  'aiAgents.ts': { tools: ['list_ai_agents', 'list_ai_agent_runs', 'get_ai_agent_run', 'manage_ai_agents'] },
  'aiArtifacts.ts': { gap: '#6141' },
  'aiOperatorTasks.ts': { gap: '#6141' },
  'aiProvider.ts': { gap: '#6141' },
  'alertTemplates/correlations.ts': { gap: '#6141' },
  'alertTemplates/rules.ts': { tools: ['manage_alert_rules'] },
  'alertTemplates/templates.ts': { tools: ['manage_alert_rules'] },
  'alerts/alerts.ts': { tools: ['manage_alerts'] },
  'alerts/channels.ts': { tools: ['manage_notification_channels'] },
  'alerts/correlations.ts': { gap: '#6141' },
  'alerts/delivery.ts': { tools: ['manage_delivery'] },
  'alerts/deliveryRails.ts': { tools: ['manage_delivery'] },
  'alerts/policies.ts': { tools: ['manage_delivery'] },
  'alerts/routing.ts': { tools: ['manage_delivery'] },
  'alerts/rules.ts': { tools: ['manage_alert_rules'] },
  'analytics.ts': { tools: ['query_analytics', 'get_executive_summary'] },
  'apiKeys.ts': { exempt: 'identity' },
  'approvals.ts': { gap: '#6141' },
  'auditBaselines.ts': { gap: '#6141' },
  'auditLogs.ts': { tools: ['query_audit_log'] },
  'auth/accountDeletion.ts': { exempt: 'identity' },
  'auth/authTransitionTestControl.ts': { exempt: 'identity' },
  'auth/binding.ts': { exempt: 'identity' },
  'auth/cfAccessRedirectLogin.ts': { exempt: 'identity' },
  'auth/helpers.ts': { exempt: 'identity' },
  'auth/invite.ts': { exempt: 'identity' },
  'auth/login.ts': { exempt: 'identity' },
  'auth/loginContext.ts': { exempt: 'identity' },
  'auth/mfa.ts': { exempt: 'identity' },
  'auth/passkeys.ts': { exempt: 'identity' },
  'auth/password.ts': { exempt: 'identity' },
  'auth/phone.ts': { exempt: 'identity' },
  'auth/register.ts': { exempt: 'identity' },
  'auth/ssoDiscovery.ts': { exempt: 'identity' },
  'auth/testApproval.ts': { exempt: 'identity' },
  'auth/verifyEmail.ts': { exempt: 'identity' },
  'authenticator.ts': { exempt: 'identity' },
  'automations.ts': { tools: ['manage_automations'] },
  'backup/bmr.ts': { gap: '#6141' },
  'backup/bmrRecoveries.ts': { gap: '#6141' },
  'backup/configs.ts': { tools: ['manage_backup_configs'] },
  'backup/dashboard.ts': { tools: ['query_backups', 'get_backup_status'] },
  'backup/encryption.ts': { gap: '#6141' },
  'backup/hyperv.ts': { tools: ['query_hyperv_vms', 'get_hyperv_vm_details', 'manage_hyperv_vm', 'trigger_hyperv_backup', 'restore_hyperv_vm', 'manage_hyperv_checkpoints'] },
  'backup/jobs.ts': { tools: ['query_backups', 'trigger_backup'] },
  'backup/mssql.ts': { tools: ['query_mssql_instances', 'get_mssql_backup_status', 'trigger_mssql_backup', 'restore_mssql_database', 'verify_mssql_backup'] },
  'backup/profiles.ts': { tools: ['manage_backup_profiles'] },
  // #6008 W01 — the external backup-provider (Cove) admin surface; see
  // `vendor_console_admin` above for why none of it is agent-reachable.
  'backup/providerCustomers.ts': { exempt: 'vendor_console_admin', note: 'maps a discovered Cove customer onto a Breeze org' },
  'backup/providerDevices.ts': { exempt: 'vendor_console_admin', note: 'lists provider device rows and links one to a Breeze device' },
  'backup/providers.ts': { exempt: 'vendor_console_admin', note: 'stores and rotates the Cove console credential' },
  'backup/reconcile.ts': { gap: '#6141' },
  'backup/resilienceAuthorization.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'backup/restore.ts': { tools: ['restore_snapshot'] },
  'backup/sla.ts': { tools: ['query_backup_sla', 'get_sla_breaches', 'get_sla_compliance_report', 'configure_backup_sla'] },
  'backup/snapshots.ts': { tools: ['browse_snapshots', 'query_backups'] },
  'backup/vault.ts': { tools: ['query_vaults', 'get_vault_status', 'configure_vault', 'trigger_vault_sync'] },
  'backup/verification.ts': { gap: '#6141' },
  'backup/vmrestore.ts': { tools: ['get_vm_restore_estimate', 'restore_as_vm', 'instant_boot_vm'] },
  'backup/vss.ts': { gap: '#6141' },
  'billingProfiles.ts': { gap: '#6141' },
  'browserSecurity.ts': { tools: ['get_browser_security', 'manage_browser_policy'] },
  'c2c/configs.ts': { gap: '#6141' },
  'c2c/connections.ts': { tools: ['query_c2c_connections'] },
  'c2c/items.ts': { tools: ['search_c2c_items', 'restore_c2c_items'] },
  'c2c/jobs.ts': { tools: ['query_c2c_jobs', 'trigger_c2c_sync'] },
  'c2c/m365Auth.ts': { gap: '#6141' },
  'callerVerification.ts': { exempt: 'human_only_verification' },
  'catalog/bundles.ts': { tools: ['manage_catalog'] },
  'catalog/catalog.ts': { tools: ['search_catalog', 'get_catalog_item', 'manage_catalog'] },
  'catalog/distributors.ts': { tools: ['lookup_distributor_product'] },
  'catalog/enrich.ts': { gap: '#6141' },
  'catalog/pricing.ts': { tools: ['manage_catalog'] },
  'changes.ts': { tools: ['query_change_log'] },
  'cisHardening.ts': { tools: ['get_cis_compliance', 'get_cis_device_report', 'apply_cis_remediation'] },
  'clientAi/admin.ts': { exempt: 'addin_surface' },
  'clientAi/adminOrgs.ts': { exempt: 'addin_surface' },
  'clientAi/adminSessions.ts': { exempt: 'addin_surface' },
  'clientAi/adminTemplates.ts': { exempt: 'addin_surface' },
  'clientAi/adminUsage.ts': { exempt: 'addin_surface' },
  'clientAi/auth.ts': { exempt: 'addin_surface' },
  'clientAi/sessions.ts': { exempt: 'addin_surface' },
  'clientAi/templates.ts': { exempt: 'addin_surface' },
  'config.ts': { gap: '#6141' },
  'configurationPolicies/alertRuleTest.ts': { gap: '#6141' },
  'configurationPolicies/assignments.ts': { tools: ['apply_configuration_policy', 'remove_configuration_policy_assignment'] },
  'configurationPolicies/crud.ts': { tools: ['manage_configuration_policy', 'list_configuration_policies', 'get_configuration_policy'] },
  'configurationPolicies/featureLinks.ts': { tools: ['manage_policy_feature_link', 'manage_service_monitors'] },
  'configurationPolicies/patchJobs.ts': { tools: ['manage_patches'] },
  'configurationPolicies/resolution.ts': { tools: ['get_effective_configuration', 'preview_configuration_change', 'configuration_policy_compliance'] },
  'connectedApps.ts': { gap: '#6141' },
  'contracts/bulk.ts': { gap: '#6141' },
  'contracts/contracts.ts': { tools: ['list_contracts', 'get_contract', 'manage_contracts'] },
  'contracts/deliverables.ts': { tools: ['list_deliverables'] },
  'contracts/documents.ts': { gap: '#6141' },
  'contracts/generate.ts': { gap: '#6141' },
  'contracts/lifecycle.ts': { tools: ['manage_contracts'] },
  'contracts/lines.ts': { tools: ['manage_contracts'] },
  'contracts/periods.ts': { gap: '#6141' },
  'contracts/reports.ts': { gap: '#6141' },
  'contracts/templates.ts': { gap: '#6141' },
  'customFieldImport.ts': { gap: '#6141' },
  'customFields.ts': { tools: ['query_custom_fields'] },
  'deliverableTemplates.ts': { tools: ['list_deliverable_templates'] },
  'deployments.ts': { tools: ['manage_deployments'] },
  'desktopWs.ts': { exempt: 'internal_plumbing', note: 'WebSocket/HTTP transport for event, remote-session or tunnel traffic.' },
  'devPush.ts': { gap: '#6141' },
  'devices/actuateElevation.ts': { gap: '#6141' },
  'devices/aiOrigin.ts': { gap: '#6141' },
  'devices/alerts.ts': { tools: ['manage_alerts'] },
  'devices/anomalies.ts': { gap: '#6141' },
  'devices/billing.ts': { gap: '#6141' },
  'devices/bootMetrics.ts': { tools: ['analyze_boot_performance', 'manage_startup_items'] },
  'devices/bulkLifecycle.ts': { gap: '#6141' },
  'devices/commands.ts': { tools: ['registry_operations', 'execute_command', 'trigger_agent_restart', 'trigger_agent_upgrade'] },
  'devices/core.ts': { tools: ['query_devices', 'get_device_details', 'get_device_context', 'set_device_context', 'resolve_device_context', 'manage_tags'] },
  'devices/customFieldImport.ts': { gap: '#6141' },
  'devices/customFieldValues.ts': { tools: ['query_custom_fields'] },
  'devices/diagnose.ts': { gap: '#6141' },
  'devices/diagnosticLogs.ts': { gap: '#6141' },
  'devices/eventlogs.ts': { tools: ['search_logs', 'get_log_trends', 'detect_log_correlations'] },
  'devices/events.ts': { gap: '#6141' },
  'devices/filesystem.ts': { tools: ['analyze_disk_usage', 'disk_cleanup'] },
  // OS-native cleanup catalogs/runs are not covered by disk_cleanup's file deletion workflow.
  'devices/filesystemSystemCleanup.ts': { gap: '#6141' },
  'devices/function.ts': { gap: '#6141' },
  'devices/groups.ts': { tools: ['manage_groups'] },
  'devices/hardware.ts': { tools: ['get_ip_history', 'get_device_details'] },
  'devices/health.ts': { gap: '#6141' },
  'devices/helpers.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'devices/homebrewBootstrap.ts': { gap: '#6141' },
  'devices/links.ts': { gap: '#6141' },
  'devices/manual.ts': { gap: '#6141' },
  'devices/metrics.ts': { tools: ['analyze_metrics', 'analyze_fleet_metrics'] },
  'devices/moveOrg.ts': { gap: '#6141' },
  'devices/network.ts': { tools: ['list_network_assets'] },
  'devices/options.ts': { gap: '#6141' },
  'devices/patches.ts': { tools: ['manage_patches'] },
  'devices/posture.ts': { gap: '#6141' },
  'devices/processSamples.ts': { gap: '#6141' },
  'devices/provision.ts': { gap: '#6141' },
  'devices/removalConfig.ts': { gap: '#6141' },
  'devices/scripts.ts': { tools: ['run_script', 'get_script_execution_history'] },
  'devices/sessions.ts': { tools: ['get_active_users', 'get_user_experience_metrics'] },
  'devices/software.ts': { gap: '#6141' },
  'devices/softwareActions.ts': { gap: '#6141' },
  'devices/stats.ts': { gap: '#6141' },
  'devices/tabCounts.ts': { gap: '#6141' },
  'devices/warranty.ts': { gap: '#6141' },
  'devices/watchdogLogs.ts': { gap: '#6141' },
  'discovery.ts': { tools: ['list_network_assets', 'get_network_asset', 'network_discovery', 'get_network_asset_reachability'] },
  'discoveryAssetProbe.ts': { gap: '#6141' },
  'dnsSecurity.ts': { tools: ['get_dns_security', 'manage_dns_policy'] },
  'docs.ts': { tools: ['search_documentation'] },
  'dr.ts': { tools: ['query_dr_plans', 'get_dr_plan_details', 'get_dr_execution_status', 'execute_dr_plan', 'manage_dr_plan'] },
  'enrollmentKeys.ts': { gap: '#6141' },
  'eventWs.ts': { exempt: 'internal_plumbing', note: 'WebSocket/HTTP transport for event, remote-session or tunnel traffic.' },
  'extensionsAdmin.ts': { exempt: 'platform_admin', note: 'Extension runtime administration is platform-admin gated.' },
  'extensionsWeb.ts': { exempt: 'internal_plumbing', note: 'Extension frontend registry and signed static asset delivery.' },
  'externalServices.ts': { gap: '#6141' },
  'filters.ts': { tools: ['manage_saved_filters'] },
  'fleetDesign.ts': { gap: '#6141' },
  'fleetFindings.ts': { tools: ['get_fleet_findings'] },
  'google.ts': { gap: '#6141' },
  'groups.ts': { tools: ['manage_groups'] },
  'helper/index.ts': { exempt: 'device_helper' },
  'huntress.ts': { tools: ['get_huntress_status', 'get_huntress_incidents', 'sync_huntress_data'] },
  'incidentActions.ts': { tools: ['execute_containment'] },
  'incidents.ts': { tools: ['list_incidents', 'create_incident', 'execute_containment', 'collect_evidence', 'get_incident_timeline', 'generate_incident_report'] },
  'installer.ts': { exempt: 'internal_plumbing' },
  'integrations.ts': { gap: '#6141' },
  'internal/synthetic.ts': { exempt: 'internal_plumbing', note: 'Internal synthetic monitoring and canary cleanup endpoints.' },
  'invoices/assembly.ts': { tools: ['manage_invoices'] },
  'invoices/bulk.ts': { gap: '#6141' },
  'invoices/evidence.ts': { gap: '#6141' },
  'invoices/invoices.ts': { tools: ['list_invoices', 'get_invoice', 'manage_invoices'] },
  'invoices/lifecycle.ts': { tools: ['manage_invoices'] },
  'invoices/payments.ts': { tools: ['manage_invoices'] },
  'invoices/pdf.ts': { gap: '#6141' },
  'invoices/settings.ts': { gap: '#6141' },
  'invoices/stripe.ts': { tools: ['manage_invoices'] },
  'invoicesPublic.ts': { exempt: 'portal' },
  'lifecycle.ts': { gap: '#6141' },
  'logs.ts': { tools: ['search_logs', 'get_log_trends', 'detect_log_correlations'] },
  'm365.ts': { gap: '#6141' },
  'm365CustomerGraphActions.ts': { gap: '#6141' },
  'm365CustomerGraphRead.ts': { tools: ['m365_query_users', 'm365_query_signins', 'm365_query_intune_devices', 'm365_query_groups', 'm365_query_org', 'm365_query_sites'] },
  'maintenance.ts': { tools: ['manage_maintenance_windows'] },
  'mcpServer.ts': { exempt: 'mcp_transport' },
  'metrics.ts': { exempt: 'internal_plumbing' },
  'mobile.ts': { gap: '#6141' },
  'monitorDefinitions.conversion.ts': { exempt: 'human_only_migration', note: 'Legacy-to-monitor conversion (#6370): preview/convert/revert/retire are MFA- and governance-gated one-time migration actions a technician runs from the UI; the spec assigns them no AI tool.' },
  'monitorDefinitions.ts': { tools: ['list_monitors', 'get_monitor', 'get_monitor_activity', 'reset_monitor_escalation', 'manage_monitor_definitions'] },
  'monitoring.ts': { tools: ['query_monitors', 'get_service_monitoring_status'] },
  'monitoringAssetMetrics.ts': { gap: '#6141' },
  'monitors.ts': { tools: ['query_monitors', 'manage_monitors'] },
  'networkBaselines.ts': { tools: ['configure_network_baseline'] },
  'networkChanges.ts': { tools: ['get_network_changes', 'acknowledge_network_device'] },
  'networkKnownGuests.ts': { gap: '#6141' },
  'notifications.ts': { gap: '#6141' },
  'oauth.ts': { exempt: 'identity' },
  'oauthInteraction.ts': { exempt: 'identity' },
  'oauthWellKnown.ts': { exempt: 'identity' },
  'officeAddin/auth.ts': { exempt: 'addin_surface' },
  'officeAddin/bindingsAdmin.ts': { exempt: 'addin_surface' },
  'officeAddin/emailContext.ts': { exempt: 'addin_surface' },
  'officeAddin/tickets.ts': { exempt: 'addin_surface' },
  'officeAddin/time.ts': { exempt: 'addin_surface' },
  'onedrive.ts': { gap: '#6141' },
  'orgAccountReadiness.ts': { gap: '#6141' },
  'orgArchive.ts': { gap: '#6141' },
  'orgAuditRetentionSettings.ts': { gap: '#6141' },
  // Per-org billing profile read/write/delete; no AI tool surfaces it yet.
  'orgBillingProfile.ts': { gap: '#6141' },
  'orgContacts.ts': { tools: ['list_org_contacts', 'manage_organizations'] },
  'orgDocuments.ts': { tools: ['list_org_documents', 'manage_org_documents'] },
  'orgKeyDates.ts': { tools: ['manage_key_dates'] },
  'orgMerge.ts': { gap: '#6141' },
  'orgPortalSettings.ts': { gap: '#6141' },
  'orgPortalUsers.ts': { gap: '#6141' },
  'orgSummary.ts': { gap: '#6141' },
  'orgTicketSettings.ts': { gap: '#6141' },
  'orgs.ts': { tools: ['list_sites', 'get_site', 'list_organizations', 'manage_organizations'] },
  'packageSearch.ts': { gap: '#6141' },
  'pam.ts': { tools: ['request_elevation', 'revoke_elevation', 'get_elevation_history'] },
  'partner.ts': { gap: '#6141' },
  'partnerAiScriptPolicy.ts': { gap: '#6141' },
  'partnerApi/audit.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'partnerApi/configuration.ts': { gap: '#6141' },
  'partnerApi/contracts.ts': { gap: '#6141' },
  'partnerApi/devices.ts': { gap: '#6141' },
  'partnerApi/inventory.ts': { gap: '#6141' },
  'partnerApi/organizations.ts': { gap: '#6141' },
  'partnerApi/provisioning.ts': { gap: '#6141' },
  'partnerApi/relationships.ts': { gap: '#6141' },
  'partnerLoginBranding.ts': { gap: '#6141' },
  'partnerSendingDomains.ts': { gap: '#6141' },
  'partnerServicePrincipals.ts': { exempt: 'identity' },
  'partnerTrust.ts': { gap: '#6141' },
  'patchPlan.ts': { gap: '#6141' },
  'patchPolicies.ts': { gap: '#6141' },
  'patches/appOptions.ts': { gap: '#6141' },
  'patches/approvals.ts': { tools: ['manage_patches'] },
  'patches/compliance.ts': { tools: ['manage_patches'] },
  'patches/list.ts': { tools: ['manage_patches'] },
  'patches/operations.ts': { tools: ['manage_patches'] },
  'pax8.ts': { gap: '#6141' },
  'pax8Orders.ts': { gap: '#6141' },
  'peripheralControl.ts': { tools: ['manage_peripheral_policies', 'get_peripheral_activity', 'manage_peripheral_policy'] },
  'permissionsCatalog.ts': { gap: '#6141' },
  'playbooks.ts': { tools: ['list_playbooks', 'execute_playbook', 'get_playbook_history'] },
  'plugins.ts': { gap: '#6141' },
  'policyManagement/actions.ts': { gap: '#6141' },
  'policyManagement/compliance.ts': { tools: ['get_compliance_status'] },
  'policyManagement/crud.ts': { tools: ['query_compliance_policies'] },
  'portal/assets.ts': { exempt: 'portal' },
  'portal/auth.ts': { exempt: 'portal' },
  'portal/backups.ts': { exempt: 'portal' },
  'portal/branding.ts': { exempt: 'portal' },
  'portal/dashboard.ts': { exempt: 'portal' },
  'portal/devices.ts': { exempt: 'portal' },
  'portal/documents.ts': { exempt: 'portal' },
  'portal/featureFlags.ts': { exempt: 'portal' },
  'portal/helpers.ts': { exempt: 'portal' },
  'portal/invoices.ts': { exempt: 'portal' },
  'portal/network.ts': { exempt: 'portal' },
  'portal/profile.ts': { exempt: 'portal' },
  'portal/quotes.ts': { exempt: 'portal' },
  'portal/reports.ts': { exempt: 'portal' },
  'portal/security.ts': { exempt: 'portal' },
  'portal/service.ts': { exempt: 'portal' },
  'portal/tickets.ts': { exempt: 'portal' },
  'psa.ts': { tools: ['query_psa_status'] },
  'quotes/acceptanceEvidence.ts': { exempt: 'human_only_legal_evidence', note: 'Upload/download of the evidence file behind an on-behalf quote acceptance (#6633); the acceptance itself has no AI tool by design.' },
  'quotes/bulk.ts': { gap: '#6141' },
  'quotes/lifecycle.ts': { tools: ['manage_quotes'] },
  'quotes/quotes.ts': { tools: ['list_quotes', 'get_quote', 'manage_quotes'] },
  'quotesPublic.ts': { exempt: 'portal' },
  'reliability.ts': { gap: '#6141' },
  'remediationSuggestions.ts': { tools: ['list_remediation_suggestions'] },
  'remote/index.ts': { gap: '#6141' },
  'remote/sessions.ts': { tools: ['create_remote_session', 'list_remote_sessions'] },
  'remote/supportSessions.ts': { gap: '#6141' },
  'reports/core.ts': { tools: ['generate_report'] },
  'reports/data.ts': { tools: ['generate_report'] },
  'reports/generate.ts': { tools: ['generate_report'] },
  'reports/recipients.ts': { gap: '#6141' },
  'reports/runs.ts': { tools: ['generate_report'] },
  'roles.ts': { gap: '#6141' },
  'scriptAi.ts': { gap: '#6141' },
  'scriptBundle.ts': { gap: '#6141' },
  'scriptLibrary.ts': { tools: ['search_script_library'] },
  'scripts.ts': { tools: ['list_scripts', 'get_script_details', 'run_script', 'cancel_script_execution', 'get_script_execution_history', 'get_script_execution', 'list_script_templates'] },
  'search.ts': { gap: '#6141' },
  'security/compliance.ts': { gap: '#6141' },
  'security/dashboard.ts': { gap: '#6141' },
  'security/helpers.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'security/policies.ts': { gap: '#6141' },
  'security/posture.ts': { tools: ['get_security_posture'] },
  'security/readAuthorization.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'security/recommendations.ts': { gap: '#6141' },
  'security/recoveryKeys.ts': { gap: '#6141' },
  'security/scans.ts': { tools: ['security_scan'] },
  'security/status.ts': { gap: '#6141' },
  'security/threats.ts': { tools: ['security_scan'] },
  'sensitiveData.ts': { tools: ['get_sensitive_data_overview', 'remediate_sensitive_data'] },
  'sentinelOne.ts': { tools: ['get_s1_status', 'get_s1_threats', 's1_isolate_device', 's1_threat_action'] },
  'serviceDeliverables.ts': { tools: ['list_deliverables', 'manage_deliverables'] },
  'servicePrincipals.ts': { exempt: 'identity' },
  'snmp.ts': { gap: '#6141' },
  'software.ts': { gap: '#6141' },
  'softwareInstallMethods.ts': { gap: '#6141' },
  'softwareInventory.ts': { gap: '#6141' },
  'softwarePolicies.ts': { tools: ['get_software_compliance', 'manage_software_policy', 'manage_software_policies', 'remediate_software_violation'] },
  'softwareUploads.ts': { gap: '#6141' },
  'sso.ts': { exempt: 'identity' },
  'stripeConnect/index.ts': { gap: '#6141' },
  'supportPublic.ts': { exempt: 'portal' },
  'system.ts': { gap: '#6141' },
  'systemTools/eventLogs.ts': { gap: '#6141' },
  'systemTools/fileBrowser.ts': { tools: ['file_operations'] },
  'systemTools/helpers.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'systemTools/index.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'systemTools/processes.ts': { tools: ['manage_processes'] },
  'systemTools/registry.ts': { tools: ['registry_operations'] },
  'systemTools/scheduledTasks.ts': { tools: ['manage_scheduled_tasks'] },
  'systemTools/services.ts': { tools: ['manage_services'] },
  'tags.ts': { tools: ['manage_tags'] },
  'tenantVariables.ts': { gap: '#6141' },
  'terminalWs.ts': { exempt: 'internal_plumbing', note: 'WebSocket/HTTP transport for event, remote-session or tunnel traffic.' },
  'thirdPartyCatalog/list.ts': { gap: '#6141' },
  'thirdPartyCatalog/operations.ts': { gap: '#6141' },
  'ticketCategories.ts': { gap: '#6141' },
  'ticketChecklistTemplates.ts': { gap: '#6141' },
  'ticketConfig.ts': { gap: '#6141' },
  'tickets/aiDrafts.ts': { tools: ['manage_tickets'] },
  'tickets/attachments.ts': { gap: '#6141' },
  'tickets/bulk.ts': { gap: '#6141' },
  'tickets/checklist.ts': { tools: ['manage_tickets'] },
  'tickets/emailWebhook.ts': { exempt: 'inbound_integration', note: 'Inbound ticket email delivery callback.' },
  'tickets/export.ts': { gap: '#6141' },
  'tickets/forms.ts': { gap: '#6141' },
  'tickets/index.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'tickets/mailboxConnect.ts': { gap: '#6141' },
  'tickets/moveOrg.ts': { tools: ['manage_tickets'] },
  'tickets/parts.ts': { tools: ['list_time_entries'] },
  'tickets/ticketResponseTemplates.ts': { gap: '#6141' },
  'tickets/tickets.ts': { tools: ['manage_tickets'] },
  'timeEntries/index.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'timeEntries/suggestions.ts': { gap: '#6141' },
  'timeEntries/timeEntries.ts': { tools: ['list_time_entries', 'get_running_timer', 'get_timesheet', 'manage_tickets'] },
  'toolSources.ts': { gap: '#6141' },
  // Collector selection and diagnostic run lifecycle have no registered AI tool.
  'topology/diagnostics.ts': { gap: '#6141' },
  'topology/graphs.ts': { gap: '#6141' },
  'topology/layouts.ts': { gap: '#6141' },
  'topology/manual.ts': { gap: '#6141' },
  'topology/middleware.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  'topology/mutations.ts': { exempt: 'internal_plumbing', note: 'Authorization/helper or router composition module; the textual scanner matches context access, not a standalone endpoint.' },
  // Shared permission middleware and response/error wrappers register no endpoints.
  'topology/operations.ts': { exempt: 'internal_plumbing' },
  // Topology monitoring policy CRUD has no registered AI tool.
  'topology/policies.ts': { gap: '#6141' },
  'topology/settings.ts': { gap: '#6141' },
  // Topology probe target CRUD has no registered AI tool.
  'topology/targets.ts': { gap: '#6141' },
  // Template application preview, execution and status have no registered AI tool.
  'topology/templateApplications.ts': { gap: '#6141' },
  // The topology template library and version publishing have no registered AI tool.
  'topology/templates.ts': { gap: '#6141' },
  'tunnelHttp.ts': { exempt: 'internal_plumbing', note: 'WebSocket/HTTP transport for event, remote-session or tunnel traffic.' },
  'tunnelWs.ts': { exempt: 'internal_plumbing', note: 'WebSocket/HTTP transport for event, remote-session or tunnel traffic.' },
  'tunnels.ts': { gap: '#6141' },
  'unifi/index.ts': { gap: '#6141' },
  'updateRings.ts': { tools: ['manage_update_rings'] },
  'userRisk.ts': { tools: ['get_fleet_health', 'get_user_risk_scores', 'get_user_risk_detail', 'assign_security_training'] },
  'users.ts': { gap: '#6141' },
  'viewers/download.ts': { exempt: 'internal_plumbing' },
  'vulnerabilities.ts': { tools: ['get_vulnerability_report', 'get_device_vulnerabilities', 'remediate_vulnerability'] },
  'webhooks.ts': { tools: ['query_webhooks', 'test_webhook'] },
  'webhooks/emailProvider.ts': { exempt: 'inbound_integration' },
  'webhooks/quickbooks.ts': { exempt: 'inbound_integration' },
  'webhooks/stripe.ts': { exempt: 'inbound_integration' },
};
