/**
 * #3198 W02. The report-generation error classes, in a leaf module with no
 * value imports so `reportScope.ts` (imported by `reportGenerationService.ts`)
 * can extend them without an import cycle. Moved verbatim from
 * `reportGenerationService.ts`, which re-exports all three: production callers
 * keep importing them from there, because several suites fully mock that module
 * and an `instanceof` against a class imported from here would stop matching.
 */

/**
 * Thrown by every generation entry point for a `ReportType` whose artifact is
 * stored rather than produced on demand. Routes map it to
 * `409 { error: 'stored_artifact_only' }` — a 409, not a 400/500, because the
 * request is well-formed and the report genuinely exists; it just cannot be
 * (re)generated by anyone but its owner.
 *
 * `code` is a stable string rather than an `instanceof` check for the caller's
 * benefit: it crosses a route boundary and lands in a response body.
 */
export class StoredArtifactOnlyReportError extends Error {
  readonly code = 'stored_artifact_only';

  constructor(type: string) {
    super(`Report type ${type} is a stored artifact and cannot be generated`);
    this.name = 'StoredArtifactOnlyReportError';
  }
}

/** #3198 W01: the definition's owner axis is one this type cannot run under.
 *  Every partner-owned report throws this until W02 registers partner-capable
 *  generators, and so does org-scoped generation of a business type whose
 *  generator does not exist yet. Routes answer 400 unsupported_report_scope;
 *  the worker records a failed run with that reason. */
export class UnsupportedReportScopeError extends Error {
  readonly code = 'unsupported_report_scope';

  constructor(readonly reportType: string, readonly scope: 'organization' | 'partner') {
    super(`${reportType} cannot run at ${scope} scope`);
    this.name = 'UnsupportedReportScopeError';
  }
}

export class UnexecutableReportScopeError extends Error {
  constructor(message = 'Report execution authority is not executable') {
    super(message);
    this.name = 'UnexecutableReportScopeError';
  }
}
