// Generated by scripts/cloudcom/sync-browser-viewer.mjs; do not edit. Upstream AGPL-3.0.
import { browserFetch as fetch } from '../../browserFetch';
import { useEffect, useRef, useCallback, useState } from 'react';
import { invoke } from '../../platform';
import { type ConnectionParams } from '../lib/protocol';
import { exchangeDesktopConnectCode, exchangeVncConnectCode } from '../lib/api';
import { scaleVideoCoords, isWebRTCSupported, AgentSessionError, SessionEndedError, SESSION_ENDED_DEFAULT_MESSAGE, type AuthenticatedConnectionParams } from '../lib/webrtc';
import {
  startRevocationLeaseRenewal,
  LEASE_REVOKED_MESSAGE,
  LEASE_LOST_MESSAGE,
} from '../lib/revocationLease';
import { connectWebRTC as connectWebRTCTransport, type WebRTCSessionWrapper } from '../lib/transports/webrtc';
import { connectWebSocket as connectWebSocketTransport, type WebSocketSessionWrapper } from '../lib/transports/websocket';
import { capabilitiesFor, type TransportCapabilities } from '../lib/transports/types';
// VncSessionWrapper is type-only — no runtime import (avoids bundling novnc into the main chunk).
// connectVnc is loaded dynamically inside connectVncTransport so novnc's top-level await
// is deferred until the VNC path is actually invoked.
import type { VncSessionWrapper } from '../lib/transports/vnc';
import { createVncTunnel, closeTunnel, retryVncTunnel, type VncTunnelInfo } from '../lib/tunnel';
import { pollDesktopAccess } from '../lib/desktopAccess';
import { mapKey, getModifiers, isModifierOnly, isCapsLock, getCapsLockState } from '../lib/keymap';
import { sendPasteText, pasteFailureMessage } from '../lib/pasteText';
import { createInputCapabilitiesGate } from '../lib/inputCapabilities';
import { DEFAULT_WHEEL_ACCUMULATOR, wheelDeltaToSteps } from '../lib/wheel';
import { handleCtrlVPaste } from '../lib/clipboardPaste';
import { shouldAutoHandoffToVnc, shouldAutoHandoffToWebRTC } from '../lib/autoHandoff';
import { startFrameCounter } from '../lib/frameCounter';
import { createStatsReporter } from '../lib/statsReporter';
import ViewerToolbar from './ViewerToolbar';
import CredentialsPromptModal from './CredentialsPromptModal';

interface Props {
  closing?: boolean;
  params: ConnectionParams;
  onDisconnect: () => void;
  onError: (msg: string) => void;
}

type ConnectionStatus = 'connecting' | 'connected' | 'reconnecting' | 'disconnected' | 'error';
type Transport = 'webrtc' | 'websocket' | 'vnc';

const RECONNECT_TIMEOUT_MS = 30_000;
const RECONNECT_INTERVAL_MS = 3_000;

// How long Paste Text waits for the agent's input_capabilities reply before
// giving up and using per-character key synthesis. One control-channel
// round-trip; long enough to cover a paste fired the instant a session opens,
// short enough that an agent which never answers costs nothing noticeable.
const INPUT_CAPABILITIES_WAIT_MS = 500;

// How long a paste-failure notice stays in the toolbar.
const PASTE_NOTICE_TTL_MS = 8_000;

// Shown when the server rejects (re)connection because the session has ended
// (HTTP 401 'Session ended', Finding #5). The viewer holds a single-session
// token and cannot create a new session, so this is a terminal state — the
// operator must relaunch from the dashboard.
const SESSION_ENDED_MESSAGE =
  'This remote session has ended. Relaunch it from the Breeze dashboard.';

// #5300: a SessionEndedError carries a real server-provided reason (e.g. the
// no-video watchdog's swallowed capture error) exactly when the caller found
// one via fetchSessionEndedReason — SessionEndedError otherwise defaults to
// SESSION_ENDED_DEFAULT_MESSAGE. Keep the relaunch call-to-action either way;
// only the diagnostic clause changes.
function sessionEndedDisplayMessage(err: SessionEndedError): string {
  if (err.message && err.message !== SESSION_ENDED_DEFAULT_MESSAGE) {
    return `${err.message} Relaunch it from the Breeze dashboard.`;
  }
  return SESSION_ENDED_MESSAGE;
}

// Shown when the WebSocket upgrade was refused before it completed. The
// browser never exposes the HTTP status behind a failed handshake, so this
// covers every server-side refusal (expired/consumed ticket, revoked
// permission, another connection already owning the session, rate limit).
// Retrying is safe and always mints a brand new one-time ticket.
const HANDSHAKE_REJECTED_MESSAGE =
  'The connection was refused before it opened. Retry to reconnect.';

// Shown when this WebView has no WebRTC implementation at all, so the session
// runs on a fallback transport instead (issue #3410). This is normal on Linux,
// where the Viewer renders in webkit2gtk and WebRTC is only present if the
// distro built it with the GStreamer WebRTC plugins. Not an error — the session
// works, just without the WebRTC-only extras (audio, multi-monitor, bitrate
// control), so it is a notice rather than a failure state.
//
// Deliberately does NOT name the fallback transport: the session can start on
// WebSocket and later auto-hand-off to VNC, and naming one would either go
// stale mid-session or force the notice to be gated on the current transport —
// which is what previously hid it from every VNC session entirely.
//
// The feature list is the intersection of what the two fallbacks lose, per
// `capabilitiesFor` in lib/transports/types.ts — VNC keeps clipboard sync while
// WebSocket does not, so clipboard is deliberately not named here.
const WEBRTC_UNSUPPORTED_MESSAGE =
  'This system’s WebView has no WebRTC support, so the session is using a ' +
  'compatibility transport. Video quality is lower, and remote audio, ' +
  'multi-monitor switching, bitrate controls, Ctrl+Alt+Del and session ' +
  'switching are unavailable.';

// Module-level dedupe for the one-time connect-code exchange.
// React strict-mode in dev mounts → unmounts → remounts the component
// synchronously; each mount has a fresh `useRef`, so a component-scoped
// guard wouldn't help. A module-level Map persists across mounts and
// keys on the (sessionId, code) pair so a second mount with the same
// deep-link returns the same in-flight (or resolved) promise instead of
// posting `/connect/exchange` twice. The server-side connect code is
// strictly single-use — without this guard, the second POST would 401.
// Entries are evicted on completion + a short safety TTL so a later
// genuine retry (e.g. user re-opens the deep link) is still allowed.
type ExchangeResult = Awaited<ReturnType<typeof exchangeDesktopConnectCode>>;
const EXCHANGE_DEDUPE_TTL_MS = 60_000;
const inFlightDesktopExchanges = new Map<string, { promise: Promise<ExchangeResult>; expiresAt: number }>();

function exchangeDesktopConnectCodeOnce(
  apiUrl: string,
  sessionId: string,
  code: string
): Promise<ExchangeResult> {
  // NUL separator, written as an escape rather than a raw byte: a literal
  // NUL in the source makes git classify this file as binary, so every diff
  // on it renders as "Binary files differ" and grep silently matches nothing.
  const key = `${sessionId}\u0000${code}`;
  const now = Date.now();
  const cached = inFlightDesktopExchanges.get(key);
  if (cached && now < cached.expiresAt) {
    return cached.promise;
  }
  const promise = exchangeDesktopConnectCode(apiUrl, sessionId, code);
  inFlightDesktopExchanges.set(key, { promise, expiresAt: now + EXCHANGE_DEDUPE_TTL_MS });
  // Best-effort cleanup so the map doesn't grow unbounded.
  setTimeout(() => {
    const entry = inFlightDesktopExchanges.get(key);
    if (entry && entry.promise === promise) inFlightDesktopExchanges.delete(key);
  }, EXCHANGE_DEDUPE_TTL_MS);
  return promise;
}

export default function DesktopViewer({ params, onDisconnect, onError, closing = false }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const wsRef = useRef<WebSocketSessionWrapper | null>(null);
  const webrtcRef = useRef<WebRTCSessionWrapper | null>(null);
  const transportRef = useRef<Transport | null>(null);
  const wsCleanupRef = useRef<(() => void) | null>(null);
  const authRef = useRef<AuthenticatedConnectionParams | null>(null);
  const cancelledRef = useRef(false);
  const webrtcFallbackAttemptedRef = useRef(false);
  const pressedKeysRef = useRef<Set<string>>(new Set());
  const wheelAccRef = useRef(DEFAULT_WHEEL_ACCUMULATOR);
  const pasteCancelRef = useRef(false);
  // What the connected agent said it can do with injected text. An agent that
  // predates the input_capabilities handshake never answers, so this stays
  // unsupported and Paste Text keeps using per-character key synthesis
  // (issue #4089). Lifecycle is unit-tested in lib/inputCapabilities.test.ts.
  const inputCapabilitiesRef = useRef(createInputCapabilitiesGate());
  const userDisconnectRef = useRef(false);
  const reconnectTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const reconnectDeadlineRef = useRef<number | null>(null);
  const reconnectInFlightRef = useRef(false);
  const startReconnectRef = useRef<() => void>(() => {});
  const switchTransportRef = useRef<(target: Transport, reason?: 'user' | 'auto') => Promise<void>>(async () => {});
  const lastUserTransportChoiceAtRef = useRef<number>(0);
  const sessionRegisteredRef = useRef(false);

  // Connection-attempt generations. Both transports hand out one-time tickets,
  // so an attempt whose handshake the server refused is dead the moment it is
  // refused — anything it reports afterwards must not touch the live attempt.
  const wsAttemptRef = useRef(0);
  const vncAttemptRef = useRef(0);

  // VNC session + tunnel lifecycle
  const vncContainerRef = useRef<HTMLDivElement>(null);
  const vncSessionRef = useRef<VncSessionWrapper | null>(null);
  const activeVncTunnelIdRef = useRef<string | null>(null);
  const switchingToRef = useRef<Transport | null>(null);

  const clipboardDCRef = useRef<RTCDataChannel | null>(null);
  const lastClipboardHashRef = useRef<string>('');
  const clipboardAckMapRef = useRef<Map<string, { resolve: () => void; timer: ReturnType<typeof setTimeout> }>>(new Map());
  const webrtcMouseMovePendingRef = useRef<{ x: number; y: number } | null>(null);
  const webrtcMouseMoveRafRef = useRef<number | null>(null);
  const [status, setStatus] = useState<ConnectionStatus>('connecting');
  const [reconnectSecondsLeft, setReconnectSecondsLeft] = useState(0);
  const [transport, setTransport] = useState<Transport | null>(null);
  const [fps, setFps] = useState(0);
  const [quality, setQuality] = useState(60);
  const [scale, setScale] = useState(1.0);
  const [maxFps, setMaxFps] = useState(60);
  const [bitrate, setBitrate] = useState(2500);
  const [hostname, setHostname] = useState('');
  const [remoteOs, setRemoteOs] = useState<string | null>(null);
  const [connectedAt, setConnectedAt] = useState<Date | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [pasteProgress, setPasteProgress] = useState<{ current: number; total: number } | null>(null);
  // Transient toolbar notice for a paste that did not fully land. Deliberately
  // NOT errorMessage — that only renders behind the full-screen connection-error
  // overlay, and a failed paste must not tear down a working session.
  const [pasteNotice, setPasteNotice] = useState<string | null>(null);
  const [remapCmdCtrl, setRemapCmdCtrl] = useState(true);
  const [cursorStreamActive, setCursorStreamActive] = useState(false);
  const [monitors, setMonitors] = useState<Array<{ index: number; name: string; width: number; height: number; isPrimary: boolean }>>([]);
  const [activeMonitor, setActiveMonitor] = useState(0);
  const [sessions, setSessions] = useState<Array<{ sessionId: number; username: string; state: string; type: string; helperConnected: boolean }>>([]);
  const [activeSessionId, setActiveSessionId] = useState<number | null>(
    params.mode === 'desktop' ? (params.targetSessionId ?? null) : null
  );
  const [switchingSession, setSwitchingSession] = useState<string | null>(null);
  const switchingSessionRef = useRef(false);
  // VNC / transport-switcher state
  const [switchingTo, setSwitchingTo] = useState<Transport | null>(null);
  const [capabilities, setCapabilities] = useState<TransportCapabilities | null>(null);
  const [desktopState, setDesktopState] = useState<{ state: 'loginwindow' | 'user_session' | null; username: string | null }>({ state: null, username: null });
  const [webRTCAvailable, setWebRTCAvailable] = useState(false);
  // Whether THIS WebView can do WebRTC at all (issue #3410). Deliberately
  // distinct from `webRTCAvailable` above, which tracks whether the REMOTE
  // macOS device is in a state where WebRTC capture works.
  //
  // Two parts, because the capability is discovered in two stages. The cheap
  // `typeof` probe runs once up front; but a webkit2gtk build missing its
  // GStreamer plugins exposes the constructor and only throws on use, so the
  // rest is learned from the first real attempt.
  const [webrtcSupported] = useState(isWebRTCSupported);
  const [webrtcRuntimeUnusable, setWebrtcRuntimeUnusable] = useState(false);
  const webrtcUsable = webrtcSupported && !webrtcRuntimeUnusable;
  // The ref is what the connect/reconnect/switch paths read. They must NOT take
  // `webrtcUsable` as a dependency: it is in the connect effect's closure, and
  // flipping it would re-run that effect — a full teardown plus a second
  // connect-code exchange — at the exact moment WebRTC just failed.
  const webrtcUsableRef = useRef(webrtcSupported);
  const markWebRTCUnusable = useCallback(() => {
    webrtcUsableRef.current = false;
    setWebrtcRuntimeUnusable(true);
  }, []);
  const [webrtcNoticeDismissed, setWebrtcNoticeDismissed] = useState(false);
  const [remoteUserName, setRemoteUserName] = useState<string | null>(null);
  const [credentialsPrompt, setCredentialsPrompt] = useState<{ requiresUsername: boolean; submit: (creds: { username?: string; password: string }) => void } | null>(null);
  // Bumped every time a new WebRTC connection is established (initial connect
  // AND auto-reconnect). Effects that attach listeners to the control channel
  // must depend on this: `transport` alone stays 'webrtc' across a reconnect,
  // which previously left them bound to the dead channel — monitor list,
  // desktop-state events, and cursor-stream sync all silently stopped working
  // after any reconnect.
  const [webrtcEpoch, setWebrtcEpoch] = useState(0);
  const audioElRef = useRef<HTMLAudioElement | null>(null);
  const [audioEnabled, setAudioEnabled] = useState(false);
  const [hasAudioTrack, setHasAudioTrack] = useState(false);
  const [showRemoteCursor, setShowRemoteCursor] = useState(false);
  const cursorOverlayRef = useRef<HTMLDivElement>(null);
  const showRemoteCursorRef = useRef(false);
  // Tracks the current remote cursor CSS shape (e.g. "default", "pointer", "text").
  // Updated from the cursor data channel; applied to the video element style.
  const remoteCursorShapeRef = useRef<string>('default');

  const setTransportState = useCallback((t: Transport | null) => {
    transportRef.current = t;
    setTransport(t);
    setCapabilities(t ? capabilitiesFor(t) : null);
  }, []);

  // ── VNC connect helper ─────────────────────────────────────────────

  const connectVncTransport = useCallback(async (tunnel: VncTunnelInfo): Promise<boolean> => {
    const container = vncContainerRef.current;
    if (!container) return false;

    // Every connect attempt owns a generation. Anything an abandoned attempt
    // reports later (noVNC keeps emitting on its own RFB) is ignored so it can
    // never drive the current attempt's UI or transport.
    const attempt = ++vncAttemptRef.current;
    const isStale = () => vncAttemptRef.current !== attempt;
    // The tunnel ws-ticket is single use and is consumed by the handshake, so
    // an error that arrives before noVNC ever reported `connected` means the
    // server refused the upgrade (401/403/409/429 — a status the browser never
    // exposes). That attempt is dead and its URL can never be replayed.
    let vncOpened = false;
    let ownSession: VncSessionWrapper | null = null;

    // Tears down only this attempt's session; an older attempt's session (or a
    // session this attempt never got as far as creating) is left untouched.
    const disposeOwnSession = () => {
      const session = ownSession;
      ownSession = null;
      if (!session) return;
      if (vncSessionRef.current === session) vncSessionRef.current = null;
      session.close();
    };

    try {
      // Lazy-load the VNC transport so novnc (which uses top-level await) is only
      // bundled into a separate async chunk and doesn't land in the main bundle.
      const { connectVnc } = await import('../lib/transports/vnc');
      if (isStale()) return false;
      // Set transport BEFORE RFB construction so the container <div> is visible
      // (the JSX hides it with `hidden` when transport !== 'vnc'). Otherwise RFB
      // initializes against a 0×0 container and the canvas never renders frames.
      setTransportState('vnc');
      const session = await connectVnc(tunnel, {
        container,
        onStatus: (s) => {
          if (isStale()) return;
          if (s === 'connecting') setStatus('connecting');
          else if (s === 'connected') {
            vncOpened = true;
            setStatus('connected');
            setConnectedAt(new Date());
            setErrorMessage(null);
          } else if (s === 'disconnected') {
            setCredentialsPrompt(null);
            if (userDisconnectRef.current) {
              setStatus('disconnected');
              setConnectedAt(null);
            } else {
              // Unexpected disconnect — kick off reconnect (mirrors WebRTC/WebSocket behavior).
              startReconnectRef.current();
            }
          } else if (s === 'error') {
            setCredentialsPrompt(null);
            setStatus('error');
            setConnectedAt(null);
            if (!vncOpened) {
              // Rejected handshake: dispose only this attempt. Retrying goes
              // back through retryVncTunnel, which mints a fresh ticket.
              vncAttemptRef.current += 1;
              disposeOwnSession();
              setErrorMessage(HANDSHAKE_REJECTED_MESSAGE);
            }
          }
        },
        onError: (message) => {
          if (isStale()) return;
          setErrorMessage(message);
        },
        onCredentialsRequired: (requiresUsername, submit) => {
          if (isStale()) return;
          setCredentialsPrompt({ requiresUsername, submit });
        },
      });
      ownSession = session;
      if (isStale()) {
        disposeOwnSession();
        return false;
      }
      vncSessionRef.current = session;
      return true;
    } catch (err) {
      if (isStale()) return false;
      setErrorMessage(err instanceof Error ? err.message : 'VNC connect failed');
      return false;
    }
  }, [setTransportState]);

  useEffect(() => {
    showRemoteCursorRef.current = showRemoteCursor;
    if (!showRemoteCursor && cursorOverlayRef.current) {
      cursorOverlayRef.current.style.display = 'none';
    }
    // When switching between cursor modes, update the video element's CSS cursor.
    // In overlay mode the local cursor is hidden; otherwise show the remote shape.
    const videoEl = videoRef.current;
    if (videoEl) {
      if (showRemoteCursor) {
        videoEl.style.cursor = 'none';
      } else {
        videoEl.style.cursor = remoteCursorShapeRef.current || 'default';
      }
    }
  }, [showRemoteCursor]);

  // Frame rate tracking
  const frameCountRef = useRef(0);
  // React 19 removed the no-arg useRef overload; explicit `undefined` init.
  const fpsIntervalRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined);

  // Remote screen size (actual pixels from agent)
  const remoteScreenRef = useRef({ width: 1920, height: 1080 });

  // WebSocket JPEG decode backpressure: keep at most one decode in-flight and
  // always prefer the latest pending frame.
  const jpegDecodeInFlightRef = useRef(false);
  const jpegPendingFrameRef = useRef<ArrayBuffer | null>(null);
  // renderFrame is defined after connectWebSocket; use a ref to break the TDZ.
  const renderFrameRef = useRef<(data: ArrayBuffer) => void>(() => {});

  // ── Transport switcher ─────────────────────────────────────────────
  // Forward-declared ref so switchTransport can call connectWebRTC before
  // connectWebRTC is defined in this scope (they are mutually recursive via
  // auto-handoff).  The ref is kept in sync below after connectWebRTC is defined.
  const connectWebRTCRef = useRef<(auth: AuthenticatedConnectionParams, targetSessionId?: number) => Promise<boolean>>(async () => false);

  const switchTransport = useCallback(async (target: Transport, reason: 'user' | 'auto' = 'auto') => {
    if (reason === 'user') {
      lastUserTransportChoiceAtRef.current = Date.now();
    }
    if (switchingToRef.current !== null) {
      // Another switch is in progress — don't start a competing one.
      return;
    }
    if (transportRef.current === target) return;
    // Never tear down a working session to switch to a transport this WebView
    // cannot run (issue #3410). Backstop only: the toolbar already hides or
    // disables both WebRTC affordances via `transportAvailability`, and the
    // macOS auto-handoff is gated the same way, so reaching this means one of
    // those gates has drifted — hence error, not warn. A silent return here
    // would be a dead click with no feedback at all.
    if (target === 'webrtc' && !webrtcUsableRef.current) {
      console.error('Ignoring switch to WebRTC: this WebView has no RTCPeerConnection. A UI gate should have prevented this.');
      return;
    }
    const auth = authRef.current;
    if (!auth) return;

    // Stop any pending reconnect so attemptReconnect can't fire mid-switch.
    if (reconnectTimerRef.current) {
      clearInterval(reconnectTimerRef.current);
      reconnectTimerRef.current = null;
    }
    reconnectDeadlineRef.current = null;
    setReconnectSecondsLeft(0);
    reconnectInFlightRef.current = false;
    setCredentialsPrompt(null);

    switchingToRef.current = target;
    setSwitchingTo(target);
    setStatus('connecting');

    // Tear down current VNC session + tunnel before switching
    const prevVnc = vncSessionRef.current;
    vncSessionRef.current = null;
    prevVnc?.close();
    if (activeVncTunnelIdRef.current) {
      const tunnelId = activeVncTunnelIdRef.current;
      activeVncTunnelIdRef.current = null;
      void closeTunnel(tunnelId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
    }

    // Tear down current WebRTC session
    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    webrtcMouseMovePendingRef.current = null;
    const prevRtc = webrtcRef.current;
    webrtcRef.current = null;
    prevRtc?.close();

    // Tear down WebSocket
    wsCleanupRef.current?.();
    wsCleanupRef.current = null;

    setTransportState(null);

    try {
      if (target === 'vnc') {
        if (!auth.deviceId) throw new Error('deviceId required for VNC switch');
        // Browser-originated viewers carry a full JWT and go through the
        // public POST /tunnels route. Deep-link viewers carry a purpose=
        // 'viewer' token which POST /tunnels rejects (authMiddleware); use
        // the viewer-token downgrade endpoint instead. We detect viewer
        // tokens by the presence of a sessionId — the initial VNC deep
        // link arrives with sessionId=='', which also works but that path
        // already has an open tunnel so it doesn't hit this branch.
        let tunnel: VncTunnelInfo;
        let tunnelAuth = auth;
        if (auth.sessionId) {
          const res = await fetch(`${auth.apiUrl}/api/v1/vnc-viewer/downgrade-to-vnc`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${auth.accessToken}` },
          });
          if (!res.ok) {
            const body = await res.json().catch(() => null) as { error?: string } | null;
            throw new Error(body?.error ?? `Downgrade to VNC failed (${res.status})`);
          }
          const body = await res.json() as { tunnelId: string; wsUrl: string; accessToken: string };
          tunnel = { tunnelId: body.tunnelId, wsUrl: body.wsUrl };
          // sessionId stays '' after a VNC switch so the next WebRTC
          // handoff knows to mint a fresh desktop session via the upgrade
          // endpoint instead of reusing a stale (or worse, tunnel-shaped)
          // id. The tunnel id is tracked in activeVncTunnelIdRef below.
          tunnelAuth = { ...auth, sessionId: '', accessToken: body.accessToken };
          authRef.current = tunnelAuth;
        } else {
          tunnel = await createVncTunnel(auth.deviceId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
        }
        activeVncTunnelIdRef.current = tunnel.tunnelId;
        const ok = await connectVncTransport(tunnel);
        if (!ok) throw new Error('VNC connect failed');
      } else if (target === 'webrtc') {
        setWebRTCAvailable(false);
        // VNC-originated viewers arrive with sessionId='' (see the vnc mode
        // branch in the connect effect). To hand off to WebRTC we need a real
        // `remote_sessions.id` and a desktop-scoped viewer token. The
        // upgrade endpoint creates both using the current viewer token.
        let webrtcAuth = auth;
        if (!auth.sessionId) {
          const res = await fetch(`${auth.apiUrl}/api/v1/vnc-viewer/upgrade-to-webrtc`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${auth.accessToken}` },
          });
          if (!res.ok) {
            const body = await res.json().catch(() => null) as { error?: string } | null;
            throw new Error(body?.error ?? `Upgrade to WebRTC failed (${res.status})`);
          }
          const { sessionId, accessToken } = await res.json() as { sessionId: string; accessToken: string };
          webrtcAuth = { ...auth, sessionId, accessToken };
          authRef.current = webrtcAuth;
        }
        const ok = await connectWebRTCRef.current(webrtcAuth);
        if (!ok) throw new Error('WebRTC connect failed');
      }
      // websocket switching not wired here — only webrtc/vnc are in the switcher
    } catch (err) {
      // If we created a tunnel during this attempt, close it now — the caller
      // won't get a chance to.
      if (target === 'vnc' && activeVncTunnelIdRef.current) {
        void closeTunnel(activeVncTunnelIdRef.current, {
          apiUrl: auth.apiUrl,
          accessToken: auth.accessToken,
        });
        activeVncTunnelIdRef.current = null;
      }
      setErrorMessage(`Failed to switch to ${target}: ${err instanceof Error ? err.message : String(err)}`);
      setStatus('error');
    } finally {
      switchingToRef.current = null;
      setSwitchingTo(null);
    }
  }, [connectVncTransport, setTransportState]);

  // ── WebRTC connection ──────────────────────────────────────────────

  const defaultTargetSessionId = params.mode === 'desktop' ? params.targetSessionId : undefined;

  const connectWebRTC = useCallback(async (auth: AuthenticatedConnectionParams, targetSessionId?: number): Promise<boolean> => {
    const videoEl = videoRef.current;
    if (!videoEl) return false;

    const sessionWrapper = await connectWebRTCTransport(auth, {
      videoElement: videoEl,
      cursorOverlayRef,
      targetSessionId: targetSessionId ?? defaultTargetSessionId,
      showRemoteCursorRef,
      remoteCursorShapeRef,
      onConnected: () => {
        // Guard: ignore stale session events after the ref has moved on
        if (webrtcRef.current !== sessionWrapper) return;
        setStatus('connected');
        setConnectedAt(new Date());
        setErrorMessage(null);
        // Ensure keyboard input is captured without an extra click.
        videoRef.current?.focus();
      },
      onDisconnected: () => {
        if (webrtcRef.current !== sessionWrapper) return;
        if (userDisconnectRef.current) return;
        startReconnectRef.current();
      },
      onFailed: () => {
        if (webrtcRef.current !== sessionWrapper) return;
        if (userDisconnectRef.current) return;
        startReconnectRef.current();
      },
      onClosed: () => {
        if (webrtcRef.current !== sessionWrapper) return;
        if (userDisconnectRef.current) return;
        setStatus('disconnected');
        setConnectedAt(null);
      },
      onAudioTrack: (audioEl) => {
        audioElRef.current = audioEl;
        setHasAudioTrack(true);
      },
      onClipboardChannel: (channel) => {
        clipboardDCRef.current = channel;
        channel.onmessage = (msg) => {
          try {
            const payload = JSON.parse(msg.data);
            if (payload.type === 'ack' && payload.hash) {
              const entry = clipboardAckMapRef.current.get(payload.hash);
              if (entry) {
                clearTimeout(entry.timer);
                clipboardAckMapRef.current.delete(payload.hash);
                entry.resolve();
              } else {
                console.debug('[clipboard] ack for unknown hash:', payload.hash);
              }
            } else if (payload.type === 'text' && payload.text) {
              lastClipboardHashRef.current = payload.text;
              // navigator.clipboard.writeText requires a user activation in
              // WKWebView/WebView2; invoking it from an onmessage handler
              // silently rejects with NotAllowedError. Route through the
              // Tauri plugin, which goes via the Rust side and does not
              // require a gesture.
              import('../../platform').then(({ writeText }) =>
                writeText(payload.text)
              ).catch((err) => {
                console.warn('[clipboard] failed to write remote→local:', err);
              });
            }
          } catch (err) {
            console.warn('[clipboard] message handling failed:', err);
          }
        };
        channel.onclose = () => {
          clipboardDCRef.current = null;
          for (const entry of clipboardAckMapRef.current.values()) {
            clearTimeout(entry.timer);
            entry.resolve();
          }
          clipboardAckMapRef.current.clear();
        };
      },
      onCursorChannelOpen: () => setCursorStreamActive(true),
      onCursorChannelClose: () => setCursorStreamActive(false),
      onWebRTCUnsupported: markWebRTCUnusable,
    });

    if (!sessionWrapper) return false;

    webrtcRef.current = sessionWrapper;
    setWebrtcEpoch((e) => e + 1);

    // Reduce input lag under loss: coalesce mouse moves, avoid unbounded buffering.
    try {
      sessionWrapper.inputChannel.onbufferedamountlow = () => {
        if (webrtcMouseMovePendingRef.current && webrtcMouseMoveRafRef.current === null) {
          webrtcMouseMoveRafRef.current = requestAnimationFrame(flushWebRTCMouseMove);
        }
      };
    } catch {
      // Some environments may not support onbufferedamountlow.
    }

    setTransportState('webrtc');
    // Hostname is already set from the exchange response before connectWebRTC is called.
    // Connection state will flip to 'connected' via onConnected callback.
    return true;
  }, [defaultTargetSessionId, markWebRTCUnusable]);

  // Keep the forward ref in sync so switchTransport can call the latest version.
  connectWebRTCRef.current = connectWebRTC;

  // ── WebSocket connection (fallback) ────────────────────────────────

  const connectWebSocket = useCallback(async (auth: AuthenticatedConnectionParams) => {
    const canvasEl = canvasRef.current;
    if (!canvasEl) return null;

    // The transport now resolves only after the socket has opened, so the
    // callbacks below can fire before `wsRef` has been pointed at this
    // wrapper. Gate on the attempt generation instead of wrapper identity:
    // it is valid from construction, and `wsCleanupRef` bumps it on teardown
    // so a disposed attempt goes inert.
    const attempt = ++wsAttemptRef.current;
    const isStale = () => wsAttemptRef.current !== attempt;

    const sessionWrapper = await connectWebSocketTransport(auth, {
      canvasElement: canvasEl,
      onConnected: ({ hostname: deviceHostname, osType }) => {
        if (isStale()) return;
        setStatus('connected');
        setHostname(deviceHostname);
        if (osType) setRemoteOs(osType);
        invoke('update_session_hostname', { hostname: deviceHostname }).catch((err) => {
          console.warn('Failed to update session hostname:', err);
        });
        setConnectedAt(new Date());
        setErrorMessage(null);
        canvasRef.current?.focus();
      },
      onDisconnected: () => {
        if (isStale()) return;
        setConnectedAt(null);
        if (!userDisconnectRef.current) {
          startReconnectRef.current();
        } else {
          setStatus('disconnected');
        }
      },
      onError: (message) => {
        if (isStale()) return;
        setStatus('error');
        setConnectedAt(null);
        setErrorMessage(message);
        onError(message);
      },
      onFrame: (data) => {
        if (isStale()) return;
        renderFrameRef.current(data);
      },
    });

    // A stale attempt's result must never be installed — the caller has
    // already moved on to a newer connection.
    if (isStale()) {
      sessionWrapper?.close();
      return null;
    }

    if (!sessionWrapper) {
      // Either the ticket could not be minted or the handshake was refused
      // before the upgrade. Both leave the one-time ticket spent; a retry
      // re-enters this function and mints a fresh one.
      setStatus('error');
      setErrorMessage(HANDSHAKE_REJECTED_MESSAGE);
      onError(HANDSHAKE_REJECTED_MESSAGE);
      return null;
    }

    wsRef.current = sessionWrapper;
    wsCleanupRef.current = () => {
      wsAttemptRef.current += 1;
      wsRef.current = null;
      wsCleanupRef.current = null;
      sessionWrapper.close();
    };

    setTransportState('websocket');

    return wsCleanupRef.current;
  }, [onError]);

  // ── Reconnect logic (refs to break circular deps with hooks defined later) ──

  const stopReconnect = useCallback(() => {
    if (reconnectTimerRef.current) {
      clearInterval(reconnectTimerRef.current);
      reconnectTimerRef.current = null;
    }
    reconnectDeadlineRef.current = null;
    setReconnectSecondsLeft(0);
  }, []);

  // releaseAllKeys is defined after sendInputFn; use ref to break TDZ
  const releaseAllKeysRef = useRef<() => void>(() => {});

  const attemptReconnect = useCallback(async () => {
    const auth = authRef.current;
    if (!auth || cancelledRef.current || userDisconnectRef.current) {
      stopReconnect();
      return;
    }
    if (reconnectInFlightRef.current) return;
    if (switchingToRef.current !== null) {
      // A transport switch is in progress — skip this reconnect tick.
      // The switch will either install a new session or restore the previous.
      return;
    }

    // Check deadline
    const deadline = reconnectDeadlineRef.current;
    if (!deadline || Date.now() >= deadline) {
      stopReconnect();
      // Auto-handoff to VNC on macOS when WebRTC reconnect times out
      if (shouldAutoHandoffToVnc({
        remoteOs,
        deviceId: auth.deviceId,
        currentTransport: transportRef.current,
        desktopState: null,
        userJustSwitchedAt: lastUserTransportChoiceAtRef.current,
      })) {
        void switchTransportRef.current('vnc', 'auto');
        return;
      }
      setStatus('disconnected');
      setConnectedAt(null);
      setErrorMessage('Reconnection timed out');
      return;
    }

    setReconnectSecondsLeft(Math.max(0, Math.ceil((deadline - Date.now()) / 1000)));

    // Tear down old connections
    releaseAllKeysRef.current();
    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    webrtcMouseMovePendingRef.current = null;
    wsCleanupRef.current?.();
    wsCleanupRef.current = null;
    const oldRtc = webrtcRef.current;
    webrtcRef.current = null;
    oldRtc?.close();

    reconnectInFlightRef.current = true;
    const recordedTransport = transportRef.current;
    // No transport recorded — the drop beat the first successful connect. Default
    // to WebRTC, except on a WebView that has none: there WebSocket is the only
    // transport that can ever come back, and retrying WebRTC would burn the
    // entire 30s reconnect window on attempts that cannot succeed (issue #3410).
    const originalTransport: Transport = recordedTransport ?? (webrtcUsableRef.current ? 'webrtc' : 'websocket');
    if (!recordedTransport) {
      console.warn(`Reconnect: transport ref was null, defaulting to ${originalTransport}`);
    }
    try {
      if (originalTransport === 'websocket') {
        // Original connection was WebSocket — reconnect with WS only
        const cleanup = await connectWebSocket(auth);
        if (cancelledRef.current || userDisconnectRef.current) {
          cleanup?.();
          return;
        }
        if (cleanup) {
          wsCleanupRef.current = cleanup;
          stopReconnect();
        }
      } else if (originalTransport === 'vnc') {
        // Original connection was VNC — tear down stale session/tunnel and re-establish
        if (!auth.deviceId) {
          stopReconnect();
          setStatus('disconnected');
          return;
        }
        vncSessionRef.current?.close();
        vncSessionRef.current = null;
        const burntTunnelId = activeVncTunnelIdRef.current;
        activeVncTunnelIdRef.current = null;
        if (cancelledRef.current || userDisconnectRef.current) {
          if (burntTunnelId) {
            void closeTunnel(burntTunnelId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
          }
          return;
        }
        // Discards the spent tunnel/ticket first — the previous wsUrl carried a
        // one-time ticket and can never be replayed, whether the handshake was
        // refused or the session simply dropped.
        const tunnel = await retryVncTunnel(burntTunnelId, auth.deviceId, {
          apiUrl: auth.apiUrl,
          accessToken: auth.accessToken,
        });
        activeVncTunnelIdRef.current = tunnel.tunnelId;
        const ok = await connectVncTransport(tunnel);
        if (cancelledRef.current || userDisconnectRef.current) return;
        if (ok) stopReconnect();
        // If !ok, the next interval tick retries.
      } else {
        // Original connection was WebRTC (or unknown) — reconnect with WebRTC only
        const webrtcOk = await connectWebRTC(auth);
        if (cancelledRef.current || userDisconnectRef.current) return;

        if (webrtcOk) {
          stopReconnect();
        }
        // If WebRTC fails, let the interval retry — don't fall back to WS
      }
    } catch (err) {
      // Session ended/revoked server-side (401) — retrying the same sessionId
      // is futile. Stop the loop and surface a clear terminal state so the
      // operator knows to relaunch from the dashboard instead of seeing an
      // opaque error or the loop hammering the dead endpoint (Finding #5, C2).
      if (err instanceof SessionEndedError) {
        userDisconnectRef.current = true; // suppress further auto-reconnect triggers
        stopReconnect();
        setStatus('error');
        setConnectedAt(null);
        const msg = sessionEndedDisplayMessage(err);
        setErrorMessage(msg);
        onError(msg);
        reconnectInFlightRef.current = false;
        return;
      }
      if (err instanceof AgentSessionError) {
        stopReconnect();
        setStatus('error');
        setConnectedAt(null);
        setErrorMessage(err.message);
        onError(err.message);
        reconnectInFlightRef.current = false;
        return;
      }
      console.warn('Reconnect attempt failed (will retry):', err);
    } finally {
      reconnectInFlightRef.current = false;
    }
  }, [connectWebRTC, connectWebSocket, connectVncTransport, stopReconnect, remoteOs]);

  const startReconnect = useCallback(() => {
    if (!authRef.current || userDisconnectRef.current) return;

    // Don't start if already reconnecting
    if (reconnectTimerRef.current) return;

    setStatus('reconnecting');
    const deadline = Date.now() + RECONNECT_TIMEOUT_MS;
    reconnectDeadlineRef.current = deadline;
    setReconnectSecondsLeft(Math.ceil(RECONNECT_TIMEOUT_MS / 1000));

    // First attempt immediately
    void attemptReconnect();

    // Then retry every interval
    reconnectTimerRef.current = setInterval(() => {
      void attemptReconnect();
    }, RECONNECT_INTERVAL_MS);
  }, [attemptReconnect]);

  // Keep refs in sync so callbacks inside earlier useCallback closures use the latest version
  startReconnectRef.current = startReconnect;
  switchTransportRef.current = switchTransport;

  // ── Connection lifecycle ───────────────────────────────────────────

  useEffect(() => {
    // Per-invocation cancel flag. Using a local variable (not the shared ref)
    // ensures that when params change, the OLD connect() sees cancelled=true
    // even after the NEW effect body resets cancelledRef for its own connect().
    let cancelled = false;
    cancelledRef.current = false;
    webrtcFallbackAttemptedRef.current = false;
    userDisconnectRef.current = false;
    reconnectInFlightRef.current = false;
    authRef.current = null;
    wheelAccRef.current = DEFAULT_WHEEL_ACCUMULATOR;
    setCursorStreamActive(false);

    // Kill any stale reconnect timer from a previous session (e.g. when
    // App.tsx replaces params via a new deep link while reconnecting).
    stopReconnect();

    // Ensure any previous transport is fully torn down before connecting.
    releaseAllKeys();
    wsCleanupRef.current?.();
    wsCleanupRef.current = null;
    wsRef.current?.close();
    wsRef.current = null;
    // Null ref before close to prevent stale onconnectionstatechange handlers
    const prevWebrtc = webrtcRef.current;
    webrtcRef.current = null;
    prevWebrtc?.close();

    setStatus('connecting');
    setTransportState(null);
    setHostname('');
    setConnectedAt(null);
    setErrorMessage(null);

    async function connect() {
      // VNC deep link — exchange the short-lived connect code for credentials + tunnel info.
      if (params.mode === 'vnc') {
        const exchange = await exchangeVncConnectCode(params.apiUrl, params.code);
        if (cancelled) return;
        if (!exchange) {
          setStatus('error');
          onError('Invalid or expired VNC connect code');
          return;
        }
        authRef.current = {
          sessionId: '',
          apiUrl: params.apiUrl,
          accessToken: exchange.accessToken,
          deviceId: exchange.deviceId,
        };
        setRemoteOs('macos'); // VNC is macOS-only for now
        activeVncTunnelIdRef.current = exchange.tunnelId;
        const ok = await connectVncTransport({ tunnelId: exchange.tunnelId, wsUrl: exchange.wsUrl });
        if (cancelled) return;
        if (!ok) {
          // Viewer stays mounted on error; close the tunnel we own so it doesn't
          // linger on the server until idle-reaper TTL.
          if (activeVncTunnelIdRef.current) {
            void closeTunnel(activeVncTunnelIdRef.current, {
              apiUrl: params.apiUrl,
              accessToken: exchange.accessToken,
            });
            activeVncTunnelIdRef.current = null;
          }
          setStatus('error');
          onError('Failed to start VNC session');
        }
        return;
      }

      // Desktop connect-code flow.
      // Use the module-level dedupe wrapper so React strict-mode double-mount
      // (dev) doesn't fire a second POST against the now-consumed code.
      try {
        const exchange = await exchangeDesktopConnectCodeOnce(
          params.apiUrl,
          params.sessionId,
          params.connectCode
        );
        if (cancelled) return;

        if (!exchange?.accessToken) {
          setStatus('error');
          setErrorMessage('Invalid or expired connection code');
          setConnectedAt(null);
          onError('Invalid or expired connection code');
          return;
        }

        const authParams: AuthenticatedConnectionParams = {
          sessionId: params.sessionId,  // narrowed: params.mode === 'desktop' guard above
          apiUrl: params.apiUrl,
          accessToken: exchange.accessToken,
          ...(params.deviceId ? { deviceId: params.deviceId } : {}),
        };
        authRef.current = authParams;

        // Set hostname + OS from exchange response (available for all transports)
        if (exchange.hostname) {
          setHostname(exchange.hostname);
          // Window title set from Rust in update_session_hostname
          invoke('update_session_hostname', { hostname: exchange.hostname }).catch((err) => {
            console.warn('Failed to update session hostname:', err);
          });
        }
        if (exchange.osType) {
          setRemoteOs(exchange.osType);
        }

        // Try WebRTC first — unless this WebView has no WebRTC at all, in which
        // case skip straight to WebSocket rather than paying a doomed signalling
        // round trip on every connect and reconnect (issue #3410).
        const webrtcOk = webrtcUsableRef.current ? await connectWebRTC(authParams) : false;
        if (cancelled) {
          webrtcRef.current?.close();
          webrtcRef.current = null;
          return;
        }

        if (!webrtcOk) {
          // Fall back to WebSocket
          const cleanup = await connectWebSocket(authParams);
          if (cancelled) {
            cleanup?.();
            return;
          }
          wsCleanupRef.current = cleanup;
        }
      } catch (err) {
        if (cancelled) return;
        console.error('Remote desktop connect failed:', err);
        // A SessionEndedError on the initial connect means the session was
        // already ended/revoked — show the terminal message and don't let the
        // reconnect loop spin on a dead sessionId (Finding #5, C2).
        if (err instanceof SessionEndedError) {
          userDisconnectRef.current = true;
          stopReconnect();
          setStatus('error');
          const msg = sessionEndedDisplayMessage(err);
          setErrorMessage(msg);
          setConnectedAt(null);
          onError(msg);
          return;
        }
        const msg = err instanceof Error ? err.message : 'Connection failed';
        setStatus('error');
        setErrorMessage(msg);
        setConnectedAt(null);
        onError(msg);
      }
    }

    connect();

    // FPS counter
    fpsIntervalRef.current = setInterval(() => {
      setFps(frameCountRef.current);
      frameCountRef.current = 0;
    }, 1000);

    return () => {
      cancelled = true;
      cancelledRef.current = true;
      stopReconnect();
      reconnectInFlightRef.current = false;

      // Best-effort: release keys before closing the transport.
      releaseAllKeys();

      if (webrtcMouseMoveRafRef.current !== null) {
        cancelAnimationFrame(webrtcMouseMoveRafRef.current);
        webrtcMouseMoveRafRef.current = null;
      }
      webrtcMouseMovePendingRef.current = null;

      clearInterval(fpsIntervalRef.current);
      wsCleanupRef.current?.();
      wsCleanupRef.current = null;
      // Null the ref BEFORE close() so the onconnectionstatechange guard
      // (webrtcRef.current !== session) catches any synchronous state
      // change events and prevents stale reconnect triggers.
      const oldWebrtc = webrtcRef.current;
      webrtcRef.current = null;
      oldWebrtc?.close();

      // Close VNC session and tunnel on unmount
      const oldVnc = vncSessionRef.current;
      vncSessionRef.current = null;
      oldVnc?.close();
      if (activeVncTunnelIdRef.current) {
        const tunnelId = activeVncTunnelIdRef.current;
        activeVncTunnelIdRef.current = null;
        const auth = authRef.current;
        if (auth) {
          void closeTunnel(tunnelId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
        }
      }

      for (const entry of clipboardAckMapRef.current.values()) {
        clearTimeout(entry.timer);
        entry.resolve();
      }
      clipboardAckMapRef.current.clear();

	      if (sessionRegisteredRef.current) {
	        sessionRegisteredRef.current = false;
	        invoke('unregister_session').catch((err) => {
	          console.error('Failed to unregister desktop session on unmount:', err);
	        });
	      }
	    };
	  }, [connectWebRTC, connectWebSocket, connectVncTransport, onError, params, stopReconnect]);

  // Mark a window as "session active" only when fully connected.
  // Pass session_id so Rust can detect duplicate deep links for the same session.
	  useEffect(() => {
	    if (status === 'connected' && !sessionRegisteredRef.current) {
	      sessionRegisteredRef.current = true;
	      if (params.mode === 'desktop') {
	        invoke('register_session', { sessionId: params.sessionId }).catch((err) => {
	          console.error('Failed to register desktop session:', err);
	        });
	        if (params.deviceId) {
	          invoke('register_device', { deviceId: params.deviceId }).catch((err) => {
	            console.error('Failed to register desktop device:', err);
	          });
	        }
	      } else {
	        // VNC mode: register by deviceId so duplicate-link detection works.
	        invoke('register_device', { deviceId: params.deviceId }).catch((err) => {
	          console.error('Failed to register vnc device:', err);
	        });
	      }
	      return;
	    }
	    if (status !== 'connected' && status !== 'reconnecting' && sessionRegisteredRef.current) {
	      sessionRegisteredRef.current = false;
	      invoke('unregister_session').catch((err) => {
	        console.error('Failed to unregister desktop session:', err);
	      });
	    }
	  }, [
	    status,
	    params.mode,
	    params.mode === 'desktop' ? params.sessionId : params.tunnelId,
	    params.deviceId,
	  ]);

  // Revocation-lease renewal. A live session is peer-to-peer, so once the
  // answer arrives the server has no other way to reach this viewer: every 25s
  // we ask it to re-verify that this operator is still authorized for this
  // session. A definitive "no" (403/410) closes the connection here as well as
  // agent-side; an inconclusive answer rides the 90s grace window, so an API or
  // network blip cannot end a session.
  //
  // Runs for every desktop transport (WebRTC and the WebSocket fallback) —
  // both stream the screen and inject input, so both must be revokable.
  useEffect(() => {
    if (params.mode !== 'desktop') return;
    if (status !== 'connected') return;
    const auth = authRef.current;
    if (!auth?.sessionId || !auth.accessToken) return;

    const endSession = (message: string) => {
      userDisconnectRef.current = true; // no auto-reconnect onto a dead session
      stopReconnect();
      const prevRtc = webrtcRef.current;
      webrtcRef.current = null;
      prevRtc?.close();
      wsCleanupRef.current?.();
      wsCleanupRef.current = null;
      setStatus('error');
      setConnectedAt(null);
      setErrorMessage(message);
      onError(message);
    };

    return startRevocationLeaseRenewal(
      {
        apiUrl: auth.apiUrl,
        sessionId: auth.sessionId,
        accessToken: auth.accessToken,
      },
      {
        onRevoked: () => endSession(LEASE_REVOKED_MESSAGE),
        onLost: () => endSession(LEASE_LOST_MESSAGE),
      },
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status, params.mode, stopReconnect, onError]);

  // Count WebRTC video frames for the FPS readout. See lib/frameCounter.ts
  // for the rVFC-with-watchdog-fallback strategy: some WebViews (notably
  // WKWebView on macOS) expose requestVideoFrameCallback but never invoke it
  // for a WebRTC MediaStream, which otherwise left this reading a permanent
  // 0 FPS while the picture was visibly updating (issue #5292).
  useEffect(() => {
    if (transport !== 'webrtc') return;
    const videoEl = videoRef.current;
    if (!videoEl) return;

    const counter = startFrameCounter({
      video: videoEl,
      onFrame: () => { frameCountRef.current++; },
      log: (message) => console.debug('[DesktopViewer]', message),
    });
    return () => counter.stop();
  }, [transport]);

  // Request a keyframe when the viewer window/tab regains focus so the
  // picture is immediately sharp (avoids stale/artifact-y decoded frames).
  useEffect(() => {
    if (transport !== 'webrtc') return;
    const onFocus = () => {
      const ch = webrtcRef.current?.controlChannel;
      if (ch && ch.readyState === 'open') {
        ch.send(JSON.stringify({ type: 'request_keyframe' }));
      }
    };
    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') onFocus();
    };
    window.addEventListener('focus', onFocus);
    document.addEventListener('visibilitychange', onVisibilityChange);
    return () => {
      window.removeEventListener('focus', onFocus);
      document.removeEventListener('visibilitychange', onVisibilityChange);
    };
  }, [transport]);

  // WebRTC stats polling — reports ICE candidate pair, RTT, jitter, and packet
  // loss every second. Sends stats to the agent via the control channel so they
  // ship through the agent's log pipeline AND drive the agent's adaptive
  // bitrate controller (its only input — if these stop, bitrate freezes).
  // The reporter re-reads webrtcRef on every tick so it follows auto-reconnects
  // to the new PeerConnection instead of polling the dead one (see
  // lib/statsReporter.ts).
  useEffect(() => {
    if (transport !== 'webrtc') return;
    const stop = createStatsReporter({
      getConnection: () => webrtcRef.current,
      log: (summary) => console.log(`[WebRTC stats] ${summary}`),
    });
    return stop;
  }, [transport]);

  // Request monitor list and listen for control channel responses (WebRTC only)
	  useEffect(() => {
	    if (transport !== 'webrtc') return;
	    const ch = webrtcRef.current?.controlChannel;
	    if (!ch) return;

	    const onOpen = () => {
	      ch.send(JSON.stringify({ type: 'list_monitors' }));
	      ch.send(JSON.stringify({ type: 'list_sessions' }));
	      // Ask what this agent can do with pasted text. An agent that predates
	      // type_text has no case for this and no default branch, so it simply
	      // never answers and Paste Text keeps its old behaviour.
	      inputCapabilitiesRef.current.arm();
	      ch.send(JSON.stringify({ type: 'input_capabilities' }));
	    };
    const onMessage = (e: MessageEvent) => {
      try {
        const msg = JSON.parse(e.data);
        switch (msg.type) {
          case 'monitors':
            if (Array.isArray(msg.monitors)) setMonitors(msg.monitors);
            break;
          case 'sessions':
            if (Array.isArray(msg.sessions)) setSessions(msg.sessions);
            break;
          case 'monitor_switched':
            setActiveMonitor(msg.index ?? 0);
            // Request a keyframe so the browser decoder gets a fresh IDR
            // with the new resolution's SPS/PPS immediately.
            ch.send(JSON.stringify({ type: 'request_keyframe' }));
            break;
          case 'sas_result':
            if (!msg.ok) console.warn('SAS failed:', msg.error);
            if (msg.ok && msg.verificationSupported && !msg.verified) {
              console.warn('SAS request was sent but secure-desktop transition was not observed');
            }
            break;
          case 'lock_result':
            if (!msg.ok) console.warn('Lock workstation failed:', msg.error);
            break;
          case 'input_capabilities':
            inputCapabilitiesRef.current.apply(msg);
            break;
          // Sent only when a paste did NOT fully land. The progress indicator
          // completes on send, not on delivery, so without this the operator
          // could not tell a dropped paste from a successful one.
          case 'type_text_result':
            if (msg.ok === false) setPasteNotice(pasteFailureMessage(msg));
            break;
          // Agent's live WebRTC control-channel event uses `'loginwindow'` (no underscore).
          // The persisted DesktopAccessMode enum uses `'login_window'` (with underscore).
          // Do NOT unify without updating both producers. See:
          //   - agent/internal/remote/desktop/desktop_state_broadcast.go (event)
          //   - packages/shared/src/types/index.ts (DesktopAccessMode)
          case 'desktop_state':
            setDesktopState({ state: msg.state ?? null, username: msg.username ?? null });
            if (
              msg.state === 'loginwindow' &&
              shouldAutoHandoffToVnc({
                remoteOs,
                deviceId: authRef.current?.deviceId,
                currentTransport: transportRef.current,
                desktopState: 'loginwindow',
                userJustSwitchedAt: lastUserTransportChoiceAtRef.current,
              })
            ) {
              stopReconnect();
              setCredentialsPrompt(null);
              void switchTransportRef.current?.('vnc', 'auto');
            }
            break;
        }
      } catch (err) {
        console.warn('Failed to parse control message:', err);
      }
    };

    if (ch.readyState === 'open') {
      onOpen();
    }
    ch.addEventListener('open', onOpen);
    ch.addEventListener('message', onMessage);

    const sessionPollInterval = setInterval(() => {
      if (ch.readyState === 'open') {
        ch.send(JSON.stringify({ type: 'list_sessions' }));
      }
    }, 30_000);

	    return () => {
	      ch.removeEventListener('open', onOpen);
	      ch.removeEventListener('message', onMessage);
	      clearInterval(sessionPollInterval);
	      // This control channel is gone; the next one re-runs the handshake.
	      // Release anything waiting on the old answer so a paste can't hang.
	      inputCapabilitiesRef.current.release();
	    };
	    // webrtcEpoch: re-attach to the NEW control channel after an
	    // auto-reconnect — without it this stays bound to the dead channel and
	    // monitor list / sessions / desktop_state silently stop updating.
	  }, [transport, webrtcEpoch]);

  // Keep agent cursor streaming in sync with the local Remote Cursor toggle.
  useEffect(() => {
    if (transport !== 'webrtc') return;
    const ch = webrtcRef.current?.controlChannel;
    if (!ch) return;
    const syncCursorStream = () => {
      if (ch.readyState !== 'open') return;
      ch.send(JSON.stringify({ type: 'set_cursor_stream', value: showRemoteCursor ? 1 : 0 }));
    };
    syncCursorStream();
    ch.addEventListener('open', syncCursorStream);
    return () => {
      ch.removeEventListener('open', syncCursorStream);
    };
    // webrtcEpoch: re-sync on the NEW channel after an auto-reconnect.
  }, [showRemoteCursor, transport, webrtcEpoch]);

  // ── Desktop-access polling (VNC + macOS only) ──────────────────────
  // While connected via VNC, poll every 2s to check if WebRTC has become
  // available again (e.g. user logged back in). Surfaces to toolbar via
  // webRTCAvailable + remoteUserName state, and auto-hands off to WebRTC
  // the first time the mode transitions to `user_session`. 2s is fast
  // enough for the handoff to feel prompt while still cheap for the API.
  useEffect(() => {
    if (transport !== 'vnc' || remoteOs !== 'macos' || status !== 'connected') return;
    const auth = authRef.current;
    if (!auth?.deviceId) return;

    let cancelled = false;
    const deviceId = auth.deviceId;
    // Tracked locally so a fresh VNC session always starts with "unknown"
    // previous mode — a user who logged in before opening the viewer still
    // triggers the auto-switch on the first successful poll.
    let previousMode: 'user_session' | 'login_window' | 'unavailable' | null = null;

    const pollOnce = async () => {
      const result = await pollDesktopAccess(deviceId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
      if (cancelled) return;
      if (!result.ok) {
        if (result.reason === 'unauthorized') {
          // Token has expired or been revoked mid-session — stop polling; the user
          // will need to reconnect. Don't flip webRTCAvailable; leave the last
          // known state so the pill doesn't flicker.
          console.warn('pollDesktopAccess: authorization failed — stopping poll');
          clearInterval(interval);
          cancelled = true;
        }
        // For 'network' and 'error', silently keep trying on the next tick.
        return;
      }
      const mode = result.poll.mode;
      setWebRTCAvailable(mode === 'user_session');
      setRemoteUserName(result.poll.username);

      // Capability first, so a WebRTC-less WebView never proposes the handoff
      // at all. `shouldAutoHandoffToWebRTC` already latches on previousMode, so
      // this saves a stray backstop log per login transition rather than one
      // per 2s tick — but it keeps the decision where the other gates live
      // instead of relying on the backstop to clean up (issue #3410).
      if (webrtcUsableRef.current && shouldAutoHandoffToWebRTC({
        remoteOs,
        deviceId,
        currentTransport: transportRef.current,
        userJustSwitchedAt: lastUserTransportChoiceAtRef.current,
        previousMode,
        currentMode: mode,
      })) {
        void switchTransportRef.current?.('webrtc', 'auto');
      }
      previousMode = mode;
    };

    void pollOnce();
    const interval = setInterval(pollOnce, 2000);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [transport, remoteOs, status]);

  // ── Frame rendering (WebSocket JPEG path) ──────────────────────────

  const processJpegFrames = useCallback(async () => {
    if (jpegDecodeInFlightRef.current) return;
    jpegDecodeInFlightRef.current = true;

    try {
      while (true) {
        const data = jpegPendingFrameRef.current;
        jpegPendingFrameRef.current = null;
        if (!data) break;

        const blob = new Blob([data], { type: 'image/jpeg' });
        let bitmap: ImageBitmap;
        try {
          bitmap = await createImageBitmap(blob);
        } catch (err) {
          console.warn('JPEG frame decode failed, skipping corrupted frame:', err);
          continue;
        }

        const canvas = canvasRef.current;
        if (!canvas) {
          bitmap.close();
          continue;
        }

        const ctx = canvas.getContext('2d');
        if (!ctx) {
          bitmap.close();
          continue;
        }

        remoteScreenRef.current.width = bitmap.width;
        remoteScreenRef.current.height = bitmap.height;

        if (canvas.width !== bitmap.width || canvas.height !== bitmap.height) {
          canvas.width = bitmap.width;
          canvas.height = bitmap.height;
        }

        ctx.drawImage(bitmap, 0, 0);
        bitmap.close();
        frameCountRef.current++;
      }
    } finally {
      jpegDecodeInFlightRef.current = false;

      // If a frame arrived right as we finished, kick the loop again.
      if (jpegPendingFrameRef.current) {
        Promise.resolve().then(() => { void processJpegFrames(); });
      }
    }
  }, []);

  const renderFrame = useCallback((data: ArrayBuffer) => {
    // Overwrite any pending frame; we only care about the latest.
    jpegPendingFrameRef.current = data;
    if (!jpegDecodeInFlightRef.current) {
      void processJpegFrames();
    }
  }, [processJpegFrames]);
  // Keep the ref in sync so connectWebSocket (defined earlier) always calls the latest version.
  renderFrameRef.current = renderFrame;

  // Map browser pixel coordinates to remote screen coordinates.
  const scaleCoordsFn = useCallback((clientX: number, clientY: number) => {
    if (transport === 'webrtc') {
      const videoEl = videoRef.current;
      if (!videoEl) return { x: 0, y: 0 };
      return scaleVideoCoords(clientX, clientY, videoEl);
    }

    // WebSocket canvas path
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0, y: 0 };

    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / rect.width;
    const scaleY = canvas.height / rect.height;

    return {
      x: Math.round((clientX - rect.left) * scaleX / scale),
      y: Math.round((clientY - rect.top) * scaleY / scale),
    };
  }, [scale, transport]);

  // ── Input: send event ──────────────────────────────────────────────

  const sendInputFn = useCallback((event: Record<string, unknown>) => {
    const t = transportRef.current;
    if (t === 'webrtc') {
      const ch = webrtcRef.current?.inputChannel;
      if (ch && ch.readyState === 'open') {
        ch.send(JSON.stringify(event));
      }
      return;
    }

    const wsSession = wsRef.current;
    if (wsSession) {
      wsSession.inputChannel.send(JSON.stringify(event));
    }
  }, []);

  const releaseAllKeys = useCallback(() => {
    const keys = Array.from(pressedKeysRef.current);
    if (keys.length === 0) return;
    for (const key of keys) {
      sendInputFn({ type: 'key_up', key });
    }
    pressedKeysRef.current.clear();
  }, [sendInputFn]);
  releaseAllKeysRef.current = releaseAllKeys;

  const flushWebRTCMouseMove = useCallback(() => {
    webrtcMouseMoveRafRef.current = null;
    const pending = webrtcMouseMovePendingRef.current;
    if (!pending) return;

    const session = webrtcRef.current;
    if (!session) return;
    const ch = session.inputChannel;
    if (!ch || ch.readyState !== 'open') return;

    const maxBuffered = 512 * 1024;
    if (ch.bufferedAmount > maxBuffered) return; // wait for bufferedamountlow

    webrtcMouseMovePendingRef.current = null;
    ch.send(JSON.stringify({ type: 'mouse_move', x: pending.x, y: pending.y }));
  }, []);

  // Native wheel handler to enable preventDefault on non-passive listener
  useEffect(() => {
    if (!transport) return;
    const el = transport === 'webrtc' ? videoRef.current : canvasRef.current;
    if (!el) return;

    function onWheel(event: Event) {
      const e = event as WheelEvent;
      e.preventDefault();
      const r = wheelDeltaToSteps(wheelAccRef.current, e.deltaY, e.deltaMode);
      wheelAccRef.current = r.acc;
      if (r.steps === 0) return;
      const { x, y } = scaleCoordsFn(e.clientX, e.clientY);
      sendInputFn({ type: 'mouse_scroll', x, y, delta: r.steps });
    }

    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [transport, scaleCoordsFn, sendInputFn]);

  // ── Input: mouse handlers ──────────────────────────────────────────

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    const { x, y } = scaleCoordsFn(e.clientX, e.clientY);
    if (transport === 'webrtc') {
      webrtcMouseMovePendingRef.current = { x, y };
      if (webrtcMouseMoveRafRef.current === null) {
        webrtcMouseMoveRafRef.current = requestAnimationFrame(flushWebRTCMouseMove);
      }
      return;
    }
    sendInputFn({ type: 'mouse_move', x, y });
  }, [flushWebRTCMouseMove, scaleCoordsFn, sendInputFn, transport]);

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    // preventDefault on mousedown suppresses the browser's default focus behavior,
    // so explicitly re-focus the video/canvas to ensure keyboard events are captured.
    (e.currentTarget as HTMLElement).focus();
    // Flush any pending RAF mouse_move so the cursor is at the correct
    // position when the button press fires (consistent with mouseup).
    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    const pending = webrtcMouseMovePendingRef.current;
    if (pending) {
      webrtcMouseMovePendingRef.current = null;
      sendInputFn({ type: 'mouse_move', x: pending.x, y: pending.y });
    }
    const { x, y } = scaleCoordsFn(e.clientX, e.clientY);
    const button = e.button === 2 ? 'right' : e.button === 1 ? 'middle' : 'left';
    sendInputFn({ type: 'mouse_down', x, y, button });
  }, [scaleCoordsFn, sendInputFn]);

  const handleMouseUp = useCallback((e: React.MouseEvent) => {
    // Flush any pending RAF mouse_move so the final drag position arrives
    // before mouse_up — ensures the selection endpoint is correct.
    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    const pending = webrtcMouseMovePendingRef.current;
    if (pending) {
      webrtcMouseMovePendingRef.current = null;
      sendInputFn({ type: 'mouse_move', x: pending.x, y: pending.y });
    }
    const { x, y } = scaleCoordsFn(e.clientX, e.clientY);
    const button = e.button === 2 ? 'right' : e.button === 1 ? 'middle' : 'left';
    sendInputFn({ type: 'mouse_up', x, y, button });
  }, [scaleCoordsFn, sendInputFn]);

  const handleContextMenu = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
  }, []);

  // ── Input: paste as keystrokes ────────────────────────────────────

  const handlePasteAsKeystrokes = useCallback(async () => {
    let text: string;
    try {
      // Use Tauri native clipboard to bypass macOS "Allow Paste" prompt
      const { readText } = await import('../../platform');
      text = await readText();
    } catch (tauriErr) {
      console.warn('Tauri clipboard read failed, trying browser API:', tauriErr);
      try {
        text = await navigator.clipboard.readText();
      } catch (browserErr) {
        console.warn('Browser clipboard read also failed:', browserErr);
        return;
      }
    }
    if (!text) return;

    // The handshake is sent the moment the control channel opens, but a paste
    // fired immediately after (re)connect can still beat the reply. Wait
    // briefly for it rather than silently dropping to the lossy fallback.
    await inputCapabilitiesRef.current.settled(INPUT_CAPABILITIES_WAIT_MS);

    const control = transportRef.current === 'webrtc' ? webrtcRef.current?.controlChannel : undefined;
    pasteCancelRef.current = false;
    setPasteNotice(null);

    try {
      await sendPasteText({
        text,
        supportsTypeText: inputCapabilitiesRef.current.supportsTypeText(),
        // type_text rides the reliable control channel: the input channel is
        // created with maxRetransmits: 0, so a dropped datagram would silently
        // truncate the paste.
        sendControl: control && control.readyState === 'open' ? (json: string) => control.send(json) : null,
        sendInput: event => sendInputFn({ ...event }),
        onProgress: setPasteProgress,
        isCancelled: () => pasteCancelRef.current,
        yieldToUi: () => new Promise(r => setTimeout(r, 5)),
      });
    } catch (err) {
      // sendPasteText clears the progress indicator before rethrowing, so the
      // toolbar is never left showing a paste that stopped — but the operator
      // still needs to be told, or a half-delivered shell command looks like a
      // finished one.
      console.warn('Paste Text failed:', err);
      setPasteNotice('Paste failed — the text could not be sent to the remote machine.');
    }
  }, [sendInputFn]);

  // Clear the paste notice on a timer so it reads as a transient alert rather
  // than sticky chrome the operator has to dismiss.
  useEffect(() => {
    if (!pasteNotice) return;
    const timer = setTimeout(() => setPasteNotice(null), PASTE_NOTICE_TTL_MS);
    return () => clearTimeout(timer);
  }, [pasteNotice]);

  const handleCancelPaste = useCallback(() => {
    pasteCancelRef.current = true;
  }, []);

  // ── Input: keyboard handlers ───────────────────────────────────────

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    e.preventDefault();

    const ne = e.nativeEvent;
    // Every forwarded keyboard event states the Caps Lock state it was typed
    // under, so the agent sets the remote modifier flags explicitly instead of
    // inheriting whatever the remote machine had latched (issue #3595).
    const capsLock = getCapsLockState(ne);

    // Modifier keys pressed alone: forward as key_down so Shift+Click,
    // Ctrl+Click, etc. hold the modifier on the remote machine for
    // multi-select. Skip the rest of the handler (no modifiers bundle,
    // no paste shortcut — those are handled when a non-modifier follows).
    if (isModifierOnly(ne)) {
      let modKey = mapKey(ne);
      if (!modKey) return;
      if (remapCmdCtrl) {
        if (modKey === 'ctrl') modKey = 'meta';
        else if (modKey === 'meta') modKey = 'ctrl';
      }
      if (e.repeat) return;
      if (pressedKeysRef.current.has(modKey)) return;
      pressedKeysRef.current.add(modKey);
      sendInputFn({ type: 'key_down', key: modKey, capsLock });
      return;
    }

    // Caps Lock is a toggle, so it is deliberately kept OUT of pressedKeysRef:
    // it is never "held", and macOS reports it as keydown-on-engage /
    // keyup-on-disengage rather than a matched pair, so pairing bookkeeping
    // would strand it in the set and later emit a bogus release. The event is
    // still forwarded — an agent that predates #3595 keeps doing what it does
    // today with it, while a current agent reads the capsLock field and skips
    // injecting the key entirely.
    if (isCapsLock(ne)) {
      if (e.repeat) return;
      sendInputFn({ type: 'key_down', key: 'capslock', capsLock });
      return;
    }

    // Ctrl+Shift+V / Cmd+Shift+V → paste as keystrokes
    if (ne.code === 'KeyV' && ne.shiftKey && (ne.ctrlKey || ne.metaKey)) {
      handlePasteAsKeystrokes();
      return;
    }

    // Ctrl+Shift+F / Cmd+Shift+F → toggle local fullscreen. Handled client-side
    // and NOT forwarded, matching the reserved Shift-combo convention above.
    // We keep this set deliberately small: every locally-intercepted combo is
    // a keystroke the remote machine can never receive.
    if (ne.code === 'KeyF' && ne.shiftKey && (ne.ctrlKey || ne.metaKey)) {
      const fs = document.fullscreenElement
        ? document.exitFullscreen()
        : document.documentElement.requestFullscreen();
      // Best-effort, but leave a breadcrumb (parity with ViewerToolbar's
      // toggleFullscreen) so a "hotkey does nothing" report is diagnosable.
      fs.catch((err) => console.warn('Fullscreen hotkey failed:', err));
      return;
    }

    // Ctrl+V / Cmd+V → push local clipboard to remote before pasting.
    // Must await the clipboard sync BEFORE dispatching the key_press, or the
    // keystroke lands on the agent ahead of the clipboard payload and pastes
    // the previous contents.
    if (ne.code === 'KeyV' && !ne.shiftKey && (ne.ctrlKey || ne.metaKey)) {
      const dc = clipboardDCRef.current;
      const pasteKey = mapKey(ne);
      let pasteModifiers = getModifiers(ne);
      if (remapCmdCtrl && pasteModifiers.length > 0) {
        pasteModifiers = pasteModifiers.map(m =>
          m === 'ctrl' ? 'meta' : m === 'meta' ? 'ctrl' : m
        );
      }
      const dispatchPaste = () => {
        // capsLock is captured from the original event: this dispatches after
        // an await, by which point the live modifier state may have moved on.
        if (pasteKey) sendInputFn({ type: 'key_press', key: pasteKey, modifiers: pasteModifiers, capsLock });
      };
      const waitForAck = (hash: string, timeoutMs: number): Promise<void> => {
        if (!hash) return Promise.resolve();
        return new Promise<void>(resolve => {
          const timer = setTimeout(() => {
            clipboardAckMapRef.current.delete(hash);
            resolve();
          }, timeoutMs);
          clipboardAckMapRef.current.set(hash, { resolve, timer });
        });
      };
      handleCtrlVPaste({
        dc,
        readText: async () => {
          const { readText } = await import('../../platform');
          return readText();
        },
        lastHash: lastClipboardHashRef,
        dispatchPaste,
        waitForAck,
      });
      return;
    }

    const key = mapKey(ne);
    if (!key) return;

    let modifiers = getModifiers(ne);
    // Swap ctrl↔meta so Mac Cmd+C → Ctrl+C on Windows and vice versa
    if (remapCmdCtrl && modifiers.length > 0) {
      modifiers = modifiers.map(m =>
        m === 'ctrl' ? 'meta' : m === 'meta' ? 'ctrl' : m
      );
    }

    // If any modifier is held, fall back to the agent's key_press (which applies modifiers).
    // Otherwise, use key_down/key_up for proper "held key" semantics.
    if (modifiers.length > 0) {
      sendInputFn({ type: 'key_press', key, modifiers, capsLock });
      return;
    }

    if (e.repeat) return;
    if (pressedKeysRef.current.has(key)) return;
    pressedKeysRef.current.add(key);
    sendInputFn({ type: 'key_down', key, capsLock });
  }, [sendInputFn, handlePasteAsKeystrokes, remapCmdCtrl]);

  const handleKeyUp = useCallback((e: React.KeyboardEvent) => {
    e.preventDefault();

    const ne = e.nativeEvent;
    const capsLock = getCapsLockState(ne);

    // Caps Lock never enters pressedKeysRef (see handleKeyDown), so its release
    // is forwarded unconditionally rather than gated on membership. On macOS
    // this is the ONLY event fired when Caps Lock is disengaged.
    if (isCapsLock(ne)) {
      sendInputFn({ type: 'key_up', key: 'capslock', capsLock });
      return;
    }

    let key = mapKey(ne);
    if (!key) return;

    // Apply the same ctrl↔meta remap used on key_down so the agent sees
    // the matching release for the key that was pressed.
    if (isModifierOnly(ne) && remapCmdCtrl) {
      if (key === 'ctrl') key = 'meta';
      else if (key === 'meta') key = 'ctrl';
    }

    if (!pressedKeysRef.current.has(key)) return;
    pressedKeysRef.current.delete(key);
    sendInputFn({ type: 'key_up', key, capsLock });
  }, [sendInputFn, remapCmdCtrl]);

  // ── Toolbar: config changes ────────────────────────────────────────

  const handleConfigChange = useCallback((newQuality: number, newScale: number, newMaxFps: number) => {
    setQuality(newQuality);
    setScale(newScale);
    setMaxFps(newMaxFps);

    if (transport === 'websocket') {
      wsRef.current?.sendRaw(JSON.stringify({
        type: 'config',
        quality: newQuality,
        scaleFactor: newScale,
        maxFps: newMaxFps,
      }));
    } else if (transport === 'webrtc') {
      const ch = webrtcRef.current?.controlChannel;
      if (ch && ch.readyState === 'open') {
        ch.send(JSON.stringify({ type: 'set_fps', value: newMaxFps }));
      }
    }
  }, [transport]);

  const handleBitrateChange = useCallback((newBitrate: number) => {
    setBitrate(newBitrate);
    const ch = webrtcRef.current?.controlChannel;
    if (ch && ch.readyState === 'open') {
      ch.send(JSON.stringify({ type: 'set_bitrate', value: newBitrate * 1000 }));
    }
  }, []);

  const handleSwitchMonitor = useCallback((index: number) => {
    const ch = webrtcRef.current?.controlChannel;
    if (ch && ch.readyState === 'open') {
      ch.send(JSON.stringify({ type: 'switch_monitor', value: index }));
    }
  }, []);

  // Reconnects over WebRTC unconditionally, and deliberately carries no
  // `webrtcSupported` guard: it is unreachable on a WebView without WebRTC.
  // `sessions` is only ever populated from the WebRTC control channel, and the
  // toolbar hides the session switcher behind `capabilities.sessionSwitch`,
  // which is false for both fallback transports (issue #3410).
  const handleSwitchSession = useCallback(async (sessionId: number) => {
    if (switchingSessionRef.current) return;
    const auth = authRef.current;
    if (!auth) return;
    const target = sessions.find(s => s.sessionId === sessionId);
    const label = target?.username || `Session ${sessionId}`;

    switchingSessionRef.current = true;
    setSwitchingSession(label);
    stopReconnect();

    // Tear down current WebRTC session
    releaseAllKeys();

    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    webrtcMouseMovePendingRef.current = null;

    const prevSession = webrtcRef.current;
    webrtcRef.current = null;
    const audioEl = audioElRef.current;
    if (audioEl) {
      audioEl.pause();
      audioEl.srcObject = null;
      audioElRef.current = null;
    }
    prevSession?.close();

    // Reset display state
    setMonitors([]);
    setActiveMonitor(0);
    setTransportState(null);

    try {
      const ok = await connectWebRTC(auth, sessionId);
      if (!ok) throw new Error('WebRTC connection failed');
      setActiveSessionId(sessionId);
    } catch (err) {
      // Try to reconnect to the previous session so the viewer isn't dead
      const prevId = activeSessionId ?? undefined;
      try {
        const recovered = await connectWebRTC(auth, prevId);
        if (recovered) {
          setErrorMessage(`Failed to switch to ${label}. Restored previous session.`);
        } else {
          setErrorMessage(`Failed to switch to ${label} and could not restore previous session`);
          startReconnectRef.current();
        }
      } catch {
        setErrorMessage(`Failed to switch to ${label} and could not restore previous session`);
        startReconnectRef.current();
      }
    } finally {
      switchingSessionRef.current = false;
      setSwitchingSession(null);
    }
  }, [sessions, activeSessionId, connectWebRTC, releaseAllKeys, setTransportState, stopReconnect]);

  const handleToggleAudio = useCallback(() => {
    const newEnabled = !audioEnabled;
    setAudioEnabled(newEnabled);
    // Mute/unmute the audio element
    const audioEl = audioElRef.current;
    if (audioEl) {
      audioEl.muted = !newEnabled;
      if (newEnabled) audioEl.play().catch((err) => {
        console.warn('Failed to play remote audio:', err.message);
        setAudioEnabled(false); // reset UI to reflect actual state
      });
    }
    // Tell the agent to start/stop sending audio frames
    const ch = webrtcRef.current?.controlChannel;
    if (ch && ch.readyState === 'open') {
      ch.send(JSON.stringify({ type: 'toggle_audio', value: newEnabled ? 1 : 0 }));
    }
  }, [audioEnabled]);

  const handleSendKeys = useCallback((key: string, modifiers: string[]) => {
    sendInputFn({ type: 'key_press', key, modifiers });
  }, [sendInputFn]);

  const handleSendSAS = useCallback(() => {
    const ch = webrtcRef.current?.controlChannel;
    if (ch && ch.readyState === 'open') {
      ch.send(JSON.stringify({ type: 'send_sas' }));
    } else {
      console.warn('Ctrl+Alt+Del (SAS) requires WebRTC transport');
    }
  }, []);

  const handleLockWorkstation = useCallback(() => {
    const ch = webrtcRef.current?.controlChannel;
    if (ch && ch.readyState === 'open') {
      ch.send(JSON.stringify({ type: 'lock_workstation' }));
    } else {
      console.warn('Lock workstation requires WebRTC transport');
    }
  }, []);

  const handleDisconnect = useCallback(() => {
    userDisconnectRef.current = true;
    stopReconnect();
    reconnectInFlightRef.current = false;
	    if (sessionRegisteredRef.current) {
	      sessionRegisteredRef.current = false;
	      invoke('unregister_session').catch((err) => {
	        console.error('Failed to unregister desktop session on disconnect:', err);
	      });
	    }
    releaseAllKeys();

    if (webrtcMouseMoveRafRef.current !== null) {
      cancelAnimationFrame(webrtcMouseMoveRafRef.current);
      webrtcMouseMoveRafRef.current = null;
    }
    webrtcMouseMovePendingRef.current = null;

    wsCleanupRef.current?.();
    wsCleanupRef.current = null;
    // Clean up audio element to release MediaStream resources
    const audioEl = audioElRef.current;
    if (audioEl) {
      audioEl.pause();
      audioEl.srcObject = null;
      audioElRef.current = null;
    }
    const rtcSession = webrtcRef.current;
    webrtcRef.current = null;
    rtcSession?.close();
    // Close VNC session and tunnel
    const vncSession = vncSessionRef.current;
    vncSessionRef.current = null;
    vncSession?.close();
    if (activeVncTunnelIdRef.current) {
      const tunnelId = activeVncTunnelIdRef.current;
      activeVncTunnelIdRef.current = null;
      const auth = authRef.current;
      if (auth) {
        void closeTunnel(tunnelId, { apiUrl: auth.apiUrl, accessToken: auth.accessToken });
      }
    }
    onDisconnect();
  }, [onDisconnect, releaseAllKeys, stopReconnect]);

  // ── Render ─────────────────────────────────────────────────────────

  const interactionProps = {
    onMouseMove: handleMouseMove,
    onMouseDown: handleMouseDown,
    onMouseUp: handleMouseUp,
    onContextMenu: handleContextMenu,
    onKeyDown: handleKeyDown,
    onKeyUp: handleKeyUp,
  };

  useEffect(() => {
    if (!closing) return;
    userDisconnectRef.current = true;
    stopReconnect();
    releaseAllKeys();
    webrtcRef.current?.close();
    wsCleanupRef.current?.();
    vncSessionRef.current?.close();
  }, [closing, releaseAllKeys, stopReconnect]);

  return (
    <div className="flex flex-col h-screen bg-gray-900">
      <ViewerToolbar
        status={status}
        hostname={hostname}
        connectedAt={connectedAt}
        fps={fps}
        transport={transport}
        quality={quality}
        scale={scale}
        maxFps={maxFps}
        bitrate={bitrate}
        pasteProgress={pasteProgress}
        pasteNotice={pasteNotice}
        remapCmdCtrl={remapCmdCtrl}
        monitors={monitors}
        activeMonitor={activeMonitor}
        sessions={sessions}
        activeSessionId={activeSessionId}
        onSwitchSession={handleSwitchSession}
        audioEnabled={audioEnabled}
        hasAudioTrack={hasAudioTrack}
        showRemoteCursor={showRemoteCursor}
        remoteOs={remoteOs}
        onRemapCmdCtrlChange={setRemapCmdCtrl}
        onShowRemoteCursorChange={setShowRemoteCursor}
        onConfigChange={handleConfigChange}
        onBitrateChange={handleBitrateChange}
        onSwitchMonitor={handleSwitchMonitor}
        onToggleAudio={handleToggleAudio}
        onSendKeys={handleSendKeys}
        onSendSAS={handleSendSAS}
        onLockWorkstation={handleLockWorkstation}
        onPasteAsKeystrokes={handlePasteAsKeystrokes}
        onCancelPaste={handleCancelPaste}
        reconnectSecondsLeft={reconnectSecondsLeft}
        webRTCAvailable={webRTCAvailable}
        webrtcSupported={webrtcUsable}
        remoteUserName={remoteUserName}
        desktopState={desktopState}
        onSwitchTransport={(target) => switchTransport(target, 'user')}
        capabilities={capabilities}
      />
      <div className="flex-1 overflow-hidden flex items-center justify-center bg-black relative">
        {/* WebRTC: <video> element (hardware H264 decode) */}
        <video
          ref={videoRef}
          tabIndex={0}
          autoPlay
          playsInline
          muted
          className={`max-w-full max-h-full object-contain outline-hidden ${transport !== 'webrtc' ? 'hidden' : ''}`}
          style={{ cursor: cursorStreamActive && showRemoteCursor ? 'none' : 'default' }}
          {...interactionProps}
        />

        {/* Session switching overlay */}
        {switchingSession && (
          <div className="absolute inset-0 bg-black/80 flex items-center justify-center z-20">
            <div className="text-center">
              <div className="animate-spin w-8 h-8 border-2 border-accent-soft border-t-transparent rounded-full mx-auto mb-3" />
              <p className="text-white text-sm">Switching to {switchingSession}...</p>
            </div>
          </div>
        )}

        {/* Remote cursor overlay — streamed at 120Hz independent of video frame rate */}
        <div
          ref={cursorOverlayRef}
          className="absolute top-0 left-0 pointer-events-none z-50"
          style={{ display: 'none', willChange: 'transform' }}
        >
          <svg width="12" height="16" viewBox="0 0 16 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 0V19L5.5 14L9 22L12 20.5L8.5 13H15L0 0Z" fill="white" stroke="black" strokeWidth="1.5"/>
          </svg>
        </div>

        {/* WebSocket: <canvas> element (JPEG software decode) */}
        <canvas
          ref={canvasRef}
          tabIndex={0}
          className={`max-w-full max-h-full object-contain outline-hidden cursor-default ${transport !== 'websocket' ? 'hidden' : ''}`}
          {...interactionProps}
        />

        {/* VNC: noVNC container (shown only when transport is VNC) */}
        <div
          ref={vncContainerRef}
          className={`flex-1 min-h-0 w-full h-full bg-black overflow-hidden relative flex items-center justify-center ${transport !== 'vnc' ? 'hidden' : ''}`}
        />

        {/* VNC credentials prompt */}
        {credentialsPrompt && (
          <CredentialsPromptModal
            requiresUsername={credentialsPrompt.requiresUsername}
            onSubmit={(creds) => {
              credentialsPrompt.submit(creds);
              setCredentialsPrompt(null);
            }}
            onCancel={() => {
              setCredentialsPrompt(null);
              handleDisconnect();
            }}
          />
        )}

        {/* WebRTC-unsupported notice (issue #3410).
            Non-modal and dismissible: the session works, so this explains the
            degraded quality rather than blocking on it.

            Gated on the capability, NOT on the resulting transport. Keying it to
            `transport === 'websocket'` hid it from every VNC session (including
            VNC deep links, which never attempt WebRTC at all) and made it vanish
            mid-session on the macOS websocket→VNC auto-handoff. Suppressed while
            a full-screen overlay owns the view — the fatal error card and the
            "Session Ended" card. */}
        {!webrtcUsable && status !== 'error' && status !== 'disconnected' && !webrtcNoticeDismissed && (
          <div
            role="status"
            aria-live="polite"
            className="absolute top-3 left-1/2 -translate-x-1/2 z-30 max-w-xl flex items-start gap-2 px-3 py-2 rounded bg-amber-900/90 border border-amber-700 text-amber-100 text-xs shadow-lg"
          >
            <span className="flex-1">{WEBRTC_UNSUPPORTED_MESSAGE}</span>
            <button
              type="button"
              onClick={() => setWebrtcNoticeDismissed(true)}
              className="shrink-0 text-amber-400 hover:text-amber-100"
              title="Dismiss"
              aria-label="Dismiss WebRTC compatibility notice"
            >
              ✕
            </button>
          </div>
        )}

        {/* Transport-switching overlay */}
        {switchingTo && (
          <div className="absolute inset-0 bg-black/80 flex items-center justify-center z-20">
            <div className="text-center">
              <div className="animate-spin w-8 h-8 border-2 border-accent-soft border-t-transparent rounded-full mx-auto mb-3" />
              <p className="text-white text-sm">Switching to {switchingTo === 'vnc' ? 'VNC' : 'WebRTC'}…</p>
            </div>
          </div>
        )}

        {status === 'connecting' && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-900/80">
            <div className="text-center">
              <div className="animate-spin w-8 h-8 border-2 border-accent border-t-transparent rounded-full mx-auto mb-4" />
              <p className="text-gray-300">Connecting to remote desktop...</p>
            </div>
          </div>
        )}
        {status === 'reconnecting' && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-900/60 backdrop-blur-[2px]">
            <div className="text-center bg-gray-900/80 rounded-xl px-8 py-6 shadow-2xl border border-retry/50">
              <div className="animate-spin w-8 h-8 border-2 border-retry border-t-transparent rounded-full mx-auto mb-4" />
              <p className="text-gray-200 font-medium mb-1">Reconnecting...</p>
              <p className="text-gray-400 text-sm mb-4">
                {reconnectSecondsLeft > 0
                  ? `Retrying connection (${reconnectSecondsLeft}s remaining)`
                  : 'Attempting to reconnect...'}
              </p>
              <button
                onClick={handleDisconnect}
                className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded text-white text-sm"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
        {status === 'error' && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-900/80">
            <div className="text-center">
              <p className="text-red-400 mb-2">Connection Error</p>
              {errorMessage && <p className="text-gray-400 text-sm mb-4">{errorMessage}</p>}
              <div className="flex items-center justify-center gap-2">
                {/* A refused handshake is recoverable: retrying re-enters the
                    connect path, which always mints a brand new one-time
                    ticket rather than replaying the rejected URL. */}
                <button
                  onClick={() => {
                    setErrorMessage(null);
                    userDisconnectRef.current = false;
                    startReconnectRef.current();
                  }}
                  className="px-4 py-2 bg-accent hover:bg-accent-hover rounded text-white"
                >
                  Retry
                </button>
                <button
                  onClick={onDisconnect}
                  className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded text-white"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}
        {status === 'disconnected' && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-900/50 backdrop-blur-xs">
            <div className="text-center bg-gray-900/70 rounded-xl px-8 py-6 shadow-2xl border border-gray-700/50">
              <p className="text-gray-200 font-medium mb-1">Session Ended</p>
              <p className="text-gray-400 text-sm mb-4">The remote desktop connection was closed</p>
              <button
                onClick={onDisconnect}
                className="px-4 py-2 bg-accent hover:bg-accent-hover rounded text-white text-sm"
              >
                Close
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
