import { describe, it, expect } from 'vitest';
import { reportTypeSurvivesBuilder } from './ReportBuilder';

// Guards the drift the type-design review flagged: the predicate is the single
// source of truth for "can the freeform builder represent this type without
// downgrading it". If the builder's type maps change, these expectations
// should change with them — deliberately, not silently.
describe('reportTypeSurvivesBuilder', () => {
  it('returns true for types the builder round-trips losslessly', () => {
    for (const type of [
      'device_inventory',
      'software_inventory',
      'alert_summary',
      'compliance',
      'performance'
    ] as const) {
      expect(reportTypeSurvivesBuilder(type)).toBe(true);
    }
  });

  it('returns true for native builder types', () => {
    for (const type of ['devices', 'alerts', 'patches', 'compliance', 'activity'] as const) {
      expect(reportTypeSurvivesBuilder(type)).toBe(true);
    }
  });

  it('returns false for types the builder would downgrade', () => {
    // posture → compliance, executive_summary → performance
    expect(reportTypeSurvivesBuilder('security_compliance_posture')).toBe(false);
    expect(reportTypeSurvivesBuilder('executive_summary')).toBe(false);
    // ai_org_narrative → activity. The AI schedule owns this type end to end;
    // the builder must never present itself as able to author it.
    expect(reportTypeSurvivesBuilder('ai_org_narrative')).toBe(false);
    // ai_fleet_design → activity, same reasoning (Fleet Designer, W01).
    expect(reportTypeSurvivesBuilder('ai_fleet_design')).toBe(false);
    // hardware_lifecycle → devices: curated template with its own options form.
    expect(reportTypeSurvivesBuilder('hardware_lifecycle')).toBe(false);
    // threat_detection_review → devices (#5784 W02): curated type with its own
    // options form, generated by the managed-evidence system path. The builder
    // must not claim to author it.
    expect(reportTypeSurvivesBuilder('threat_detection_review')).toBe(false);
    // endpoint_management_review → devices: curated #5784 W03 evidence type
    // with its own options form; the freeform builder cannot represent the
    // Intune freshness/trend config at all.
    expect(reportTypeSurvivesBuilder('endpoint_management_review')).toBe(false);
    // vulnerability_management → compliance: curated template with its own
    // options form (severity floor, top-N, exceptions), #5784 W04.
    expect(reportTypeSurvivesBuilder('vulnerability_management')).toBe(false);
    // identity_access_review → devices (#5784 W06): curated type with its own
    // options form; the builder would downgrade it to a plain devices report.
    expect(reportTypeSurvivesBuilder('identity_access_review')).toBe(false);
    // #3198 Phase 1 business reports (W02): curated, never portal-visible, the
    // only types whose supportedScopes include 'partner' — the freeform
    // builder cannot represent any of them.
    expect(reportTypeSurvivesBuilder('ticket_sla_attainment')).toBe(false);
    expect(reportTypeSurvivesBuilder('technician_time_billability')).toBe(false);
    expect(reportTypeSurvivesBuilder('ar_aging')).toBe(false);
  });
});
